// Code generated by export_websocket_package/export_package.go; DO NOT EDIT.
package websocket

import (
	"github.com/gorilla/websocket"
)

type BufferPool = websocket.BufferPool
type CloseError = websocket.CloseError
type Conn = websocket.Conn
type Dialer = websocket.Dialer
type HandshakeError = websocket.HandshakeError
type PreparedMessage = websocket.PreparedMessage
type Upgrader = websocket.Upgrader

var BinaryMessage = websocket.BinaryMessage
var CloseAbnormalClosure = websocket.CloseAbnormalClosure
var CloseGoingAway = websocket.CloseGoingAway
var CloseInternalServerErr = websocket.CloseInternalServerErr
var CloseInvalidFramePayloadData = websocket.CloseInvalidFramePayloadData
var CloseMandatoryExtension = websocket.CloseMandatoryExtension
var CloseMessage = websocket.CloseMessage
var CloseMessageTooBig = websocket.CloseMessageTooBig
var CloseNoStatusReceived = websocket.CloseNoStatusReceived
var CloseNormalClosure = websocket.CloseNormalClosure
var ClosePolicyViolation = websocket.ClosePolicyViolation
var CloseProtocolError = websocket.CloseProtocolError
var CloseServiceRestart = websocket.CloseServiceRestart
var CloseTLSHandshake = websocket.CloseTLSHandshake
var CloseTryAgainLater = websocket.CloseTryAgainLater
var CloseUnsupportedData = websocket.CloseUnsupportedData
var PingMessage = websocket.PingMessage
var PongMessage = websocket.PongMessage
var TextMessage = websocket.TextMessage
var DefaultDialer = websocket.DefaultDialer
var ErrBadHandshake = websocket.ErrBadHandshake
var ErrCloseSent = websocket.ErrCloseSent
var ErrReadLimit = websocket.ErrReadLimit
var FormatCloseMessage = websocket.FormatCloseMessage
var IsCloseError = websocket.IsCloseError
var IsUnexpectedCloseError = websocket.IsUnexpectedCloseError
var IsWebSocketUpgrade = websocket.IsWebSocketUpgrade
var JoinMessages = websocket.JoinMessages
var NewClient = websocket.NewClient
var NewPreparedMessage = websocket.NewPreparedMessage
var ReadJSON = websocket.ReadJSON
var Subprotocols = websocket.Subprotocols
var Upgrade = websocket.Upgrade
var WriteJSON = websocket.WriteJSON

