// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/app"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/appinfo"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/bootstrap"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/client"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/config"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/database"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/job"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/kafka"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/log"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/metrics"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/redis"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/tracing"
)

import (
	_ "github.com/jaggerzhuang1994/kratos-foundation/v2/contrib/database/sqlite"
	_ "github.com/jaggerzhuang1994/kratos-foundation/v2/contrib/oss/aliyun"
)

// Injectors from wire.go:

func initialize(path configPath, version2 string) (*kratos.App, func(), error) {
	spec := bootstrap.NewSpec()
	appSpec := bootstrap.ApplicationSpec(spec)
	appInfo := appinfo.New(version2)
	appInfoBootstrap, err := bootstrap.NewAppInfoBootstrap(appInfo, appSpec)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := log.NewLogger()
	if err != nil {
		return nil, nil, err
	}
	logBootstrap, cleanup2, err := bootstrap.NewLogBootstrap(logger, appSpec)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracingBootstrap, err := bootstrap.NewTracingBootstrap()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	provider, cleanup3, err := metrics.NewProvider(appInfo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := metrics.NewMetrics(provider, appInfo)
	metricsBootstrap, err := bootstrap.NewMetricsBootstrap(appSpec, v)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sources, err := newSources(path)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager, cleanup4, err := config.NewManager(sources)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configObservabilityBootstrap, cleanup5, err := bootstrap.NewConfigObservabilityBootstrap(manager, provider)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	infrastructureBootstrap := bootstrap.NewInfrastructureBootstrap(appInfoBootstrap, logBootstrap, tracingBootstrap, metricsBootstrap, configObservabilityBootstrap)
	tracingProvider, cleanup6, err := tracing.NewProvider(manager, appInfo)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	databaseManager, cleanup7, err := database.NewManager(logger, manager, appInfo, tracingProvider, provider)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisManager, cleanup8, err := redis.NewManager(logger, manager, tracingProvider, provider)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainDataService, err := newDataService(databaseManager, redisManager, provider, logger)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainObjectStorage, cleanup9, err := newObjectStorage(manager, logger, provider)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientFactory, err := kafka.NewClientFactory(logger, manager)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainMessaging, cleanup10, err := newMessaging(redisManager, clientFactory, provider, tracingProvider, logger)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	discovery := newDiscovery()
	factory, cleanup11, err := client.NewFactory(manager, logger, appInfo, tracingProvider, provider, discovery)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainDemoService, err := newDemoService(mainDataService, mainObjectStorage, mainMessaging, factory, logger, provider)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bootstrapBootstrap, err := boot(infrastructureBootstrap, spec, mainDemoService, mainMessaging, redisManager)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	concurrencyCoordinator := job.DefaultCoordinator()
	componentsBootstrap, cleanup12, err := bootstrap.NewComponentsBootstrap(spec, manager, logger, provider, tracingProvider, bootstrapBootstrap, concurrencyCoordinator)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	startupReady := bootstrap.NewApplicationBootstrap(infrastructureBootstrap, componentsBootstrap)
	v2, err := app.NewConfig(manager)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stopPolicy, cleanup13, err := bootstrap.NewStopPolicy(v2, manager, logger, componentsBootstrap)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registrar := newRegistrar()
	kratosApp, err := bootstrap.NewKratosApp(appSpec, startupReady, v2, stopPolicy, registrar)
	if err != nil {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return kratosApp, func() {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
