// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/app"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/appinfo"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/bootstrap"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/client"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/database"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/job"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/kafka"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/log"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/metrics"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/redis"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/registry"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/server"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/tracing"
)

import (
	_ "github.com/jaggerzhuang1994/kratos-foundation/v2/contrib/database/sqlite"
	_ "github.com/jaggerzhuang1994/kratos-foundation/v2/contrib/oss/aliyun"
	_ "github.com/jaggerzhuang1994/kratos-foundation/v2/contrib/registry/consul"
)

// Injectors from wire.go:

func initialize(path configPath, version2 string) (*kratos.App, func(), error) {
	spec := app.NewSpec()
	serverSpec := server.NewSpec()
	jobSpec := job.NewSpec()
	bootstrapSpec, err := newSpec(spec, serverSpec, jobSpec, path)
	if err != nil {
		return nil, nil, err
	}
	manager, cleanup, err := bootstrap.NewConfigManager(bootstrapSpec)
	if err != nil {
		return nil, nil, err
	}
	v, err := app.NewConfig(manager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger, cleanup2, err := log.NewLogger()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	stopPolicy, cleanup3, err := app.NewStopPolicy(v, manager, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	factory, cleanup4, err := registry.NewFactory(manager, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registrar, err := app.NewRegistrar(v, factory)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appInfo := appinfo.New(version2)
	appInfoBootstrap := bootstrap.NewAppInfoBootstrap(spec, appInfo)
	logBootstrap, cleanup5, err := bootstrap.NewLogBootstrap(spec, manager, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tracingBootstrap, err := bootstrap.NewTracingBootstrap()
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	provider, cleanup6, err := metrics.NewProvider(appInfo)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v2 := metrics.NewMetrics(provider, appInfo)
	metricsBootstrap := bootstrap.NewMetricsBootstrap(spec, v2)
	infrastructureBootstrap := bootstrap.NewInfrastructureBootstrap(appInfoBootstrap, logBootstrap, tracingBootstrap, metricsBootstrap)
	tracingProvider, cleanup7, err := tracing.NewProvider(manager, appInfo)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	databaseManager, cleanup8, err := database.NewManager(logger, manager, appInfo, tracingProvider, provider)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisManager, cleanup9, err := redis.NewManager(logger, manager, tracingProvider, provider)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainDataService, err := newDataService(databaseManager, redisManager, provider, logger)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainObjectStorage, cleanup10, err := newObjectStorage(manager, logger, provider)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientFactory, err := kafka.NewClientFactory(logger, manager)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainMessaging, cleanup11, err := newMessaging(redisManager, clientFactory, provider, tracingProvider, logger)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	factory2, cleanup12, err := client.NewFactory(manager, logger, appInfo, tracingProvider, provider, factory)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainDemoService, err := newDemoService(mainDataService, mainObjectStorage, mainMessaging, factory2, logger, provider)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bootstrapBootstrap, err := boot(infrastructureBootstrap, bootstrapSpec, mainDemoService, mainMessaging, redisManager)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverBootstrap, cleanup13, err := bootstrap.NewServerBootstrap(spec, serverSpec, manager, logger, provider, tracingProvider)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobBootstrap, err := bootstrap.NewJobBootstrap(spec, jobSpec, manager, logger, provider, tracingProvider)
	if err != nil {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtimeBootstrap := bootstrap.NewRuntimeBootstrap(serverBootstrap, jobBootstrap)
	startupReady := bootstrap.NewApplicationBootstrap(infrastructureBootstrap, bootstrapBootstrap, runtimeBootstrap)
	kratosApp, err := bootstrap.NewKratosApp(spec, v, stopPolicy, registrar, startupReady)
	if err != nil {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return kratosApp, func() {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
