//go:generate sh -c "go run gen_default_client.go > ../default_client.go 2>&2"
package main

import (
	"fmt"
	"go/format"
	"reflect"
	"strings"

	"github.com/redis/go-redis/v9"
)

func main() {
	t := reflect.TypeOf((*redis.Client)(nil))

	src := strings.Builder{}

	src.WriteString(`// Code generated by gen_default_client.go; DO NOT EDIT.
package redis

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/redis/go-redis/v9/maintnotifications"
	"github.com/redis/go-redis/v9/push"
)

`)

	defaultClientInterface := strings.Builder{}
	defaultClientInterface.WriteString(`
type defaultClient interface {
`)
	delegateMethod := strings.Builder{}

	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		sig, argVars := genFuncSig(m)

		defaultClientInterface.WriteString(sig)
		defaultClientInterface.WriteString("\n")
		delegateMethod.WriteString(genManagerDelegateMethod(m, sig, argVars))
		delegateMethod.WriteString("\n")
	}

	defaultClientInterface.WriteString("}\n")

	src.WriteString(defaultClientInterface.String())
	src.WriteString(delegateMethod.String())

	code, err := format.Source([]byte(src.String()))
	if err != nil {
		panic(src.String())
	}

	fmt.Print(string(code))
}

// 生成 Manager 的代理方法
//
//	func (m *Manager) MethodName(args) outArgs {
//		return c.defaultConn.MethodName(args)
//	}
func genManagerDelegateMethod(m reflect.Method, sig string, argVars []string) string {
	// 返回值
	var returnExp = "return "
	mt := m.Type

	if mt.NumOut() == 0 {
		returnExp = ""
	}
	return fmt.Sprintf("func (m *manager) %s {\n\t%sm.defaultConn.%s(%s)\n}\n", sig, returnExp, m.Name, strings.Join(argVars, ", "))
}

func genFuncSig(m reflect.Method) (sig string, argVars []string) {
	mt := m.Type

	// 方法前面
	sig = fmt.Sprintf("%s (", m.Name)

	// 形参，从 1 开始
	var args = make([]string, 0, mt.NumIn()-1)
	argVars = make([]string, 0, mt.NumIn()-1)
	for i := 1; i < mt.NumIn(); i++ {
		// ...可选参数列表
		if mt.IsVariadic() && i == mt.NumIn()-1 {
			args = append(args, fmt.Sprintf("arg%d %s", i-1, strings.ReplaceAll(mt.In(i).String(), "[]", "...")))
			argVars = append(argVars, fmt.Sprintf("arg%d...", i-1))
		} else {
			args = append(args, fmt.Sprintf("arg%d %s", i-1, mt.In(i).String()))
			argVars = append(argVars, fmt.Sprintf("arg%d", i-1))
		}
	}
	sig += strings.Join(args, ", ")
	sig += ")"

	// 返回值
	switch mt.NumOut() {
	case 0: // 0个返回值
	case 1: // 1个返回值
		sig += " " + mt.Out(0).String()
	default: // >1个返回值
		sig += " ("
		var outArgs = make([]string, 0, mt.NumIn())
		for i := 0; i < mt.NumOut(); i++ {
			outArgs = append(outArgs, mt.Out(i).String())
		}
		sig += strings.Join(outArgs, ", ")
		sig += ")"
	}

	return
}
