// Code generated by protoc-gen-kratos-foundation-client. DO NOT EDIT.
// versions:
// - protoc-gen-kratos-foundation-client {{.ProtocGenGoClientRelease}}
// - protoc               {{.ProtocVersion}}
{{- if .Deprecated}}
// {{.Path}} is a deprecated file.
{{- else}}
// source: {{.Path}}
{{- end}}
package {{.GoPackageName}}

{{- range .Services}}

{{$fileServiceName := .File.ServiceName}}
{{$deprecated := .Deprecated}}

// {{.ServiceName}}Provider .
{{- if .Deprecated}}
// Deprecated: Do not use.
{{- end}}
var {{.ServiceName}}Provider = wire.NewSet(
	New{{.ServiceName}},
)
var {{.ServiceName}}HTTPImplProvider = {{.ServiceName}}Provider
var {{.ServiceName}}GRPCClientImplProvider = {{.ServiceName}}Provider

// {{.ServiceName}} .
{{- if .Deprecated}}
// Deprecated: Do not use.
{{- end}}
type {{.ServiceName}} interface {
{{- range .MethodSets}}
    {{.Comment}}
	{{.Name}}(context.Context, *{{.Request}}) (*{{.Reply}}, error)
{{- end}}
}

// {{.ServiceName}}Impl .
{{- if .Deprecated}}
// Deprecated: Do not use.
{{- end}}
type {{.ServiceName}}Impl struct {
	factory client.Factory
}

var _ {{.ServiceName}} = (*{{.ServiceName}}Impl)(nil)

// New{{.ServiceName}}Impl .
{{- if .Deprecated}}
// Deprecated: Do not use.
{{- end}}
func New{{.ServiceName}}(factory client.Factory) {{.ServiceName}} {
	return &{{.ServiceName}}Impl{factory}
}

{{range .MethodSets}}
// {{.Name}} .
{{- if $deprecated}}
// Deprecated: Do not use.
{{- end}}
func (c *{{.ServiceName}}Impl) {{.Name}}(ctx context.Context, in *{{.Request}}) (rsp *{{.Reply}}, err error) {
	ctx = client.WithDefaultConnName(ctx, "{{$fileServiceName}}")

	// 获取连接
	httpClient, grpcClient, err := c.factory.ResolveClient(ctx)
	if err != nil {
		return nil, errors.WithMessagef(err, "resolve %s client err", client.ConnNameFromContext(ctx))
	}

	// 发起请求
	if grpcClient != nil {
		opts := client.GrpcCallOptionFromContext(ctx)
		rsp, err = New{{.ServiceName}}Client(grpcClient).{{.Name}}(ctx, in, opts...)
	} else {
{{- if eq (index .Service.HttpMethodSets .Name) nil}}
    _ = httpClient
	panic("not implemented")
{{- else}}
		opts := client.HttpCallOptionFromContext(ctx)
		rsp, err = New{{.ServiceName}}HTTPClient(httpClient).{{.Name}}(ctx, in, opts...)
{{- end}}
	}
	return
}
{{end}}

{{- end}}
