// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/client.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Client with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Client) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Client with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ClientMultiError, or nil if none found.
func (m *Client) ValidateAll() error {
	return m.validate(true)
}

func (m *Client) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetClients()))
		i := 0
		for key := range m.GetClients() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetClients()[key]
			_ = val

			// no validation rules for Clients[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ClientValidationError{
							field:  fmt.Sprintf("Clients[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ClientValidationError{
							field:  fmt.Sprintf("Clients[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ClientValidationError{
						field:  fmt.Sprintf("Clients[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ClientMultiError(errors)
	}

	return nil
}

// ClientMultiError is an error wrapping multiple validation errors returned by
// Client.ValidateAll() if the designated constraints aren't met.
type ClientMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientMultiError) AllErrors() []error { return m }

// ClientValidationError is the validation error returned by Client.Validate if
// the designated constraints aren't met.
type ClientValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientValidationError) ErrorName() string { return "ClientValidationError" }

// Error satisfies the builtin error interface
func (e ClientValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClient.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientValidationError{}

// Validate checks the field values on ClientOption with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClientOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClientOption with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ClientOptionMultiError, or
// nil if none found.
func (m *ClientOption) ValidateAll() error {
	return m.validate(true)
}

func (m *ClientOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Target

	if m.Protocol != nil {
		// no validation rules for Protocol
	}

	if m.Middleware != nil {

		if all {
			switch v := interface{}(m.GetMiddleware()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientOptionValidationError{
						field:  "Middleware",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientOptionValidationError{
						field:  "Middleware",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMiddleware()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientOptionValidationError{
					field:  "Middleware",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ClientOptionMultiError(errors)
	}

	return nil
}

// ClientOptionMultiError is an error wrapping multiple validation errors
// returned by ClientOption.ValidateAll() if the designated constraints aren't met.
type ClientOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientOptionMultiError) AllErrors() []error { return m }

// ClientOptionValidationError is the validation error returned by
// ClientOption.Validate if the designated constraints aren't met.
type ClientOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientOptionValidationError) ErrorName() string { return "ClientOptionValidationError" }

// Error satisfies the builtin error interface
func (e ClientOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClientOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientOptionValidationError{}

// Validate checks the field values on ClientMiddleware with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ClientMiddleware) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClientMiddleware with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClientMiddlewareMultiError, or nil if none found.
func (m *ClientMiddleware) ValidateAll() error {
	return m.validate(true)
}

func (m *ClientMiddleware) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Timeout != nil {

		if all {
			switch v := interface{}(m.GetTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metadata != nil {

		if all {
			switch v := interface{}(m.GetMetadata()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Tracing != nil {

		if all {
			switch v := interface{}(m.GetTracing()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTracing()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "Tracing",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Logging != nil {

		if all {
			switch v := interface{}(m.GetLogging()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Logging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "Logging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLogging()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "Logging",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.CircuitBreaker != nil {

		if all {
			switch v := interface{}(m.GetCircuitBreaker()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "CircuitBreaker",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClientMiddlewareValidationError{
						field:  "CircuitBreaker",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCircuitBreaker()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClientMiddlewareValidationError{
					field:  "CircuitBreaker",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ClientMiddlewareMultiError(errors)
	}

	return nil
}

// ClientMiddlewareMultiError is an error wrapping multiple validation errors
// returned by ClientMiddleware.ValidateAll() if the designated constraints
// aren't met.
type ClientMiddlewareMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientMiddlewareMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientMiddlewareMultiError) AllErrors() []error { return m }

// ClientMiddlewareValidationError is the validation error returned by
// ClientMiddleware.Validate if the designated constraints aren't met.
type ClientMiddlewareValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientMiddlewareValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientMiddlewareValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientMiddlewareValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientMiddlewareValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientMiddlewareValidationError) ErrorName() string { return "ClientMiddlewareValidationError" }

// Error satisfies the builtin error interface
func (e ClientMiddlewareValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClientMiddleware.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientMiddlewareValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientMiddlewareValidationError{}
