// Code generated by protoc-gen-kratos-foundation-errors. DO NOT EDIT.

package config_pb

import (
	fmt "fmt"
	errors "github.com/jaggerzhuang1994/kratos-foundation/pkg/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// grpc请求
func IsGrpc(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "GRPC" && e.Metadata != nil && e.Metadata["reason_code"] == "0"
}

// grpc请求
func ErrorGrpc(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "grpc请求"
	}
	return errors.New(500, "GRPC", fmt.Sprintf(format, args...)).WithReasonCode(0).WithErrStack(4)
}

// http请求
func IsHttp(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "HTTP" && e.Metadata != nil && e.Metadata["reason_code"] == "1"
}

// http请求
func ErrorHttp(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "http请求"
	}
	return errors.New(500, "HTTP", fmt.Sprintf(format, args...)).WithReasonCode(1).WithErrStack(4)
}

// grpcs请求
func IsGrpcs(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "GRPCS" && e.Metadata != nil && e.Metadata["reason_code"] == "2"
}

// grpcs请求
func ErrorGrpcs(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "grpcs请求"
	}
	return errors.New(500, "GRPCS", fmt.Sprintf(format, args...)).WithReasonCode(2).WithErrStack(4)
}

// https请求
func IsHttps(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "HTTPS" && e.Metadata != nil && e.Metadata["reason_code"] == "3"
}

// https请求
func ErrorHttps(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "https请求"
	}
	return errors.New(500, "HTTPS", fmt.Sprintf(format, args...)).WithReasonCode(3).WithErrStack(4)
}
