// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/database.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Database with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Database) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Database with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DatabaseMultiError, or nil
// if none found.
func (m *Database) ValidateAll() error {
	return m.validate(true)
}

func (m *Database) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetConnections()))
		i := 0
		for key := range m.GetConnections() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetConnections()[key]
			_ = val

			// no validation rules for Connections[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, DatabaseValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, DatabaseValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return DatabaseValidationError{
						field:  fmt.Sprintf("Connections[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.Gorm != nil {

		if all {
			switch v := interface{}(m.GetGorm()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Gorm",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Gorm",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGorm()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DatabaseValidationError{
					field:  "Gorm",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DatabaseValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Default != nil {
		// no validation rules for Default
	}

	if m.Tracing != nil {

		if all {
			switch v := interface{}(m.GetTracing()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTracing()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DatabaseValidationError{
					field:  "Tracing",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DatabaseValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DatabaseValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DatabaseMultiError(errors)
	}

	return nil
}

// DatabaseMultiError is an error wrapping multiple validation errors returned
// by Database.ValidateAll() if the designated constraints aren't met.
type DatabaseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DatabaseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DatabaseMultiError) AllErrors() []error { return m }

// DatabaseValidationError is the validation error returned by
// Database.Validate if the designated constraints aren't met.
type DatabaseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DatabaseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DatabaseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DatabaseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DatabaseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DatabaseValidationError) ErrorName() string { return "DatabaseValidationError" }

// Error satisfies the builtin error interface
func (e DatabaseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDatabase.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DatabaseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DatabaseValidationError{}

// Validate checks the field values on GormTracing with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GormTracing) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GormTracing with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GormTracingMultiError, or
// nil if none found.
func (m *GormTracing) ValidateAll() error {
	return m.validate(true)
}

func (m *GormTracing) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.ExcludeQueryVars != nil {
		// no validation rules for ExcludeQueryVars
	}

	if m.ExcludeMetrics != nil {
		// no validation rules for ExcludeMetrics
	}

	if m.RecordStackTraceInSpan != nil {
		// no validation rules for RecordStackTraceInSpan
	}

	if m.ExcludeServerAddress != nil {
		// no validation rules for ExcludeServerAddress
	}

	if len(errors) > 0 {
		return GormTracingMultiError(errors)
	}

	return nil
}

// GormTracingMultiError is an error wrapping multiple validation errors
// returned by GormTracing.ValidateAll() if the designated constraints aren't met.
type GormTracingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormTracingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormTracingMultiError) AllErrors() []error { return m }

// GormTracingValidationError is the validation error returned by
// GormTracing.Validate if the designated constraints aren't met.
type GormTracingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormTracingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormTracingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormTracingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormTracingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormTracingValidationError) ErrorName() string { return "GormTracingValidationError" }

// Error satisfies the builtin error interface
func (e GormTracingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGormTracing.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormTracingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormTracingValidationError{}

// Validate checks the field values on GormMetrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GormMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GormMetrics with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GormMetricsMultiError, or
// nil if none found.
func (m *GormMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *GormMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Labels

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.RefreshInterval != nil {

		if all {
			switch v := interface{}(m.GetRefreshInterval()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormMetricsValidationError{
						field:  "RefreshInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormMetricsValidationError{
						field:  "RefreshInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRefreshInterval()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormMetricsValidationError{
					field:  "RefreshInterval",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Mysql != nil {

		if all {
			switch v := interface{}(m.GetMysql()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormMetricsValidationError{
						field:  "Mysql",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormMetricsValidationError{
						field:  "Mysql",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMysql()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormMetricsValidationError{
					field:  "Mysql",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GormMetricsMultiError(errors)
	}

	return nil
}

// GormMetricsMultiError is an error wrapping multiple validation errors
// returned by GormMetrics.ValidateAll() if the designated constraints aren't met.
type GormMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormMetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormMetricsMultiError) AllErrors() []error { return m }

// GormMetricsValidationError is the validation error returned by
// GormMetrics.Validate if the designated constraints aren't met.
type GormMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormMetricsValidationError) ErrorName() string { return "GormMetricsValidationError" }

// Error satisfies the builtin error interface
func (e GormMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGormMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormMetricsValidationError{}

// Validate checks the field values on Gorm with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Gorm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Gorm with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GormMultiError, or nil if none found.
func (m *Gorm) ValidateAll() error {
	return m.validate(true)
}

func (m *Gorm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.SkipDefaultTransaction != nil {
		// no validation rules for SkipDefaultTransaction
	}

	if m.DefaultTransactionTimeout != nil {

		if all {
			switch v := interface{}(m.GetDefaultTransactionTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "DefaultTransactionTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "DefaultTransactionTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDefaultTransactionTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormValidationError{
					field:  "DefaultTransactionTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DefaultContextTimeout != nil {

		if all {
			switch v := interface{}(m.GetDefaultContextTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "DefaultContextTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "DefaultContextTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDefaultContextTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormValidationError{
					field:  "DefaultContextTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.FullSaveAssociations != nil {
		// no validation rules for FullSaveAssociations
	}

	if m.Logger != nil {

		if all {
			switch v := interface{}(m.GetLogger()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "Logger",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormValidationError{
						field:  "Logger",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLogger()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormValidationError{
					field:  "Logger",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DisableAutomaticPing != nil {
		// no validation rules for DisableAutomaticPing
	}

	if m.DisableForeignKeyConstraintWhenMigrating != nil {
		// no validation rules for DisableForeignKeyConstraintWhenMigrating
	}

	if m.IgnoreRelationshipsWhenMigrating != nil {
		// no validation rules for IgnoreRelationshipsWhenMigrating
	}

	if m.DisableNestedTransaction != nil {
		// no validation rules for DisableNestedTransaction
	}

	if m.AllowGlobalUpdate != nil {
		// no validation rules for AllowGlobalUpdate
	}

	if m.QueryFields != nil {
		// no validation rules for QueryFields
	}

	if m.CreateBatchSize != nil {
		// no validation rules for CreateBatchSize
	}

	if m.TranslateError != nil {
		// no validation rules for TranslateError
	}

	if m.PropagateUnscoped != nil {
		// no validation rules for PropagateUnscoped
	}

	if len(errors) > 0 {
		return GormMultiError(errors)
	}

	return nil
}

// GormMultiError is an error wrapping multiple validation errors returned by
// Gorm.ValidateAll() if the designated constraints aren't met.
type GormMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormMultiError) AllErrors() []error { return m }

// GormValidationError is the validation error returned by Gorm.Validate if the
// designated constraints aren't met.
type GormValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormValidationError) ErrorName() string { return "GormValidationError" }

// Error satisfies the builtin error interface
func (e GormValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGorm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormValidationError{}

// Validate checks the field values on GormLogger with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GormLogger) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GormLogger with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GormLoggerMultiError, or
// nil if none found.
func (m *GormLogger) ValidateAll() error {
	return m.validate(true)
}

func (m *GormLogger) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Level != nil {
		// no validation rules for Level
	}

	if m.SlowThreshold != nil {

		if all {
			switch v := interface{}(m.GetSlowThreshold()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormLoggerValidationError{
						field:  "SlowThreshold",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormLoggerValidationError{
						field:  "SlowThreshold",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSlowThreshold()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormLoggerValidationError{
					field:  "SlowThreshold",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Colorful != nil {
		// no validation rules for Colorful
	}

	if m.IgnoreRecordNotFoundError != nil {
		// no validation rules for IgnoreRecordNotFoundError
	}

	if m.ParameterizedQueries != nil {
		// no validation rules for ParameterizedQueries
	}

	if len(errors) > 0 {
		return GormLoggerMultiError(errors)
	}

	return nil
}

// GormLoggerMultiError is an error wrapping multiple validation errors
// returned by GormLogger.ValidateAll() if the designated constraints aren't met.
type GormLoggerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormLoggerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormLoggerMultiError) AllErrors() []error { return m }

// GormLoggerValidationError is the validation error returned by
// GormLogger.Validate if the designated constraints aren't met.
type GormLoggerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormLoggerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormLoggerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormLoggerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormLoggerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormLoggerValidationError) ErrorName() string { return "GormLoggerValidationError" }

// Error satisfies the builtin error interface
func (e GormLoggerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGormLogger.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormLoggerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormLoggerValidationError{}

// Validate checks the field values on DBConnection with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DBConnection) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DBConnection with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DBConnectionMultiError, or
// nil if none found.
func (m *DBConnection) ValidateAll() error {
	return m.validate(true)
}

func (m *DBConnection) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Dsn

	for idx, item := range m.GetReplicas() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  fmt.Sprintf("Replicas[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  fmt.Sprintf("Replicas[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DBConnectionValidationError{
					field:  fmt.Sprintf("Replicas[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Driver != nil {
		// no validation rules for Driver
	}

	if m.TraceResolverMode != nil {
		// no validation rules for TraceResolverMode
	}

	if m.MaxIdleConns != nil {
		// no validation rules for MaxIdleConns
	}

	if m.MaxOpenConns != nil {
		// no validation rules for MaxOpenConns
	}

	if m.ConnMaxLifetime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxLifetime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxLifetime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DBConnectionValidationError{
					field:  "ConnMaxLifetime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ConnMaxIdleTime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxIdleTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DBConnectionValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxIdleTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DBConnectionValidationError{
					field:  "ConnMaxIdleTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DBConnectionMultiError(errors)
	}

	return nil
}

// DBConnectionMultiError is an error wrapping multiple validation errors
// returned by DBConnection.ValidateAll() if the designated constraints aren't met.
type DBConnectionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DBConnectionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DBConnectionMultiError) AllErrors() []error { return m }

// DBConnectionValidationError is the validation error returned by
// DBConnection.Validate if the designated constraints aren't met.
type DBConnectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DBConnectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DBConnectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DBConnectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DBConnectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DBConnectionValidationError) ErrorName() string { return "DBConnectionValidationError" }

// Error satisfies the builtin error interface
func (e DBConnectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDBConnection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DBConnectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DBConnectionValidationError{}

// Validate checks the field values on GormDialector with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GormDialector) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GormDialector with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GormDialectorMultiError, or
// nil if none found.
func (m *GormDialector) ValidateAll() error {
	return m.validate(true)
}

func (m *GormDialector) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Dsn

	if m.Driver != nil {
		// no validation rules for Driver
	}

	if m.MaxIdleConns != nil {
		// no validation rules for MaxIdleConns
	}

	if m.MaxOpenConns != nil {
		// no validation rules for MaxOpenConns
	}

	if m.ConnMaxLifetime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxLifetime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormDialectorValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormDialectorValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxLifetime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormDialectorValidationError{
					field:  "ConnMaxLifetime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ConnMaxIdleTime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxIdleTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormDialectorValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormDialectorValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxIdleTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormDialectorValidationError{
					field:  "ConnMaxIdleTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GormDialectorMultiError(errors)
	}

	return nil
}

// GormDialectorMultiError is an error wrapping multiple validation errors
// returned by GormDialector.ValidateAll() if the designated constraints
// aren't met.
type GormDialectorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormDialectorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormDialectorMultiError) AllErrors() []error { return m }

// GormDialectorValidationError is the validation error returned by
// GormDialector.Validate if the designated constraints aren't met.
type GormDialectorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormDialectorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormDialectorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormDialectorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormDialectorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormDialectorValidationError) ErrorName() string { return "GormDialectorValidationError" }

// Error satisfies the builtin error interface
func (e GormDialectorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGormDialector.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormDialectorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormDialectorValidationError{}

// Validate checks the field values on GormMetrics_Mysql with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GormMetrics_Mysql) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GormMetrics_Mysql with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GormMetrics_MysqlMultiError, or nil if none found.
func (m *GormMetrics_Mysql) ValidateAll() error {
	return m.validate(true)
}

func (m *GormMetrics_Mysql) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Prefix != nil {
		// no validation rules for Prefix
	}

	if m.Interval != nil {

		if all {
			switch v := interface{}(m.GetInterval()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GormMetrics_MysqlValidationError{
						field:  "Interval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GormMetrics_MysqlValidationError{
						field:  "Interval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetInterval()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GormMetrics_MysqlValidationError{
					field:  "Interval",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GormMetrics_MysqlMultiError(errors)
	}

	return nil
}

// GormMetrics_MysqlMultiError is an error wrapping multiple validation errors
// returned by GormMetrics_Mysql.ValidateAll() if the designated constraints
// aren't met.
type GormMetrics_MysqlMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GormMetrics_MysqlMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GormMetrics_MysqlMultiError) AllErrors() []error { return m }

// GormMetrics_MysqlValidationError is the validation error returned by
// GormMetrics_Mysql.Validate if the designated constraints aren't met.
type GormMetrics_MysqlValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GormMetrics_MysqlValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GormMetrics_MysqlValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GormMetrics_MysqlValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GormMetrics_MysqlValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GormMetrics_MysqlValidationError) ErrorName() string {
	return "GormMetrics_MysqlValidationError"
}

// Error satisfies the builtin error interface
func (e GormMetrics_MysqlValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGormMetrics_Mysql.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GormMetrics_MysqlValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GormMetrics_MysqlValidationError{}
