// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/discovery.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Discovery with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Discovery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Discovery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DiscoveryMultiError, or nil
// if none found.
func (m *Discovery) ValidateAll() error {
	return m.validate(true)
}

func (m *Discovery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Timeout != nil {

		if all {
			switch v := interface{}(m.GetTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DiscoveryValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DiscoveryValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DiscoveryValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Dc != nil {
		// no validation rules for Dc
	}

	if len(errors) > 0 {
		return DiscoveryMultiError(errors)
	}

	return nil
}

// DiscoveryMultiError is an error wrapping multiple validation errors returned
// by Discovery.ValidateAll() if the designated constraints aren't met.
type DiscoveryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DiscoveryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DiscoveryMultiError) AllErrors() []error { return m }

// DiscoveryValidationError is the validation error returned by
// Discovery.Validate if the designated constraints aren't met.
type DiscoveryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DiscoveryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DiscoveryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DiscoveryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DiscoveryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DiscoveryValidationError) ErrorName() string { return "DiscoveryValidationError" }

// Error satisfies the builtin error interface
func (e DiscoveryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDiscovery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DiscoveryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DiscoveryValidationError{}
