// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: config_pb/discovery.proto

package config_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DC int32

const (
	// 单数据中心
	DC_SINGLE DC = 0
	// 多数据中心
	DC_MULTI DC = 1
)

// Enum value maps for DC.
var (
	DC_name = map[int32]string{
		0: "SINGLE",
		1: "MULTI",
	}
	DC_value = map[string]int32{
		"SINGLE": 0,
		"MULTI":  1,
	}
)

func (x DC) Enum() *DC {
	p := new(DC)
	*p = x
	return p
}

func (x DC) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DC) Descriptor() protoreflect.EnumDescriptor {
	return file_config_pb_discovery_proto_enumTypes[0].Descriptor()
}

func (DC) Type() protoreflect.EnumType {
	return &file_config_pb_discovery_proto_enumTypes[0]
}

func (x DC) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DC.Descriptor instead.
func (DC) EnumDescriptor() ([]byte, []int) {
	return file_config_pb_discovery_proto_rawDescGZIP(), []int{0}
}

// 服务发现
type Discovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 获取服务的超时时间【默认10s】
	Timeout *durationpb.Duration `protobuf:"bytes,1,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	// 数据中心【默认 SINGLE】
	Dc *DC `protobuf:"varint,2,opt,name=dc,proto3,enum=kratos_foundation_pb.DC,oneof" json:"dc,omitempty"`
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_pb_discovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_config_pb_discovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery.ProtoReflect.Descriptor instead.
func (*Discovery) Descriptor() ([]byte, []int) {
	return file_config_pb_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *Discovery) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Discovery) GetDc() DC {
	if x != nil && x.Dc != nil {
		return *x.Dc
	}
	return DC_SINGLE
}

var File_config_pb_discovery_proto protoreflect.FileDescriptor

var file_config_pb_discovery_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x62, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x87, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12,
	0x38, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x02, 0x64, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x5f, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x43, 0x48,
	0x01, 0x52, 0x02, 0x64, 0x63, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x64, 0x63, 0x2a, 0x1b, 0x0a, 0x02, 0x44,
	0x43, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x10, 0x01, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x67, 0x67, 0x65, 0x72, 0x7a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x31, 0x39, 0x39, 0x34, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_pb_discovery_proto_rawDescOnce sync.Once
	file_config_pb_discovery_proto_rawDescData = file_config_pb_discovery_proto_rawDesc
)

func file_config_pb_discovery_proto_rawDescGZIP() []byte {
	file_config_pb_discovery_proto_rawDescOnce.Do(func() {
		file_config_pb_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_pb_discovery_proto_rawDescData)
	})
	return file_config_pb_discovery_proto_rawDescData
}

var file_config_pb_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_pb_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_pb_discovery_proto_goTypes = []interface{}{
	(DC)(0),                     // 0: kratos_foundation_pb.DC
	(*Discovery)(nil),           // 1: kratos_foundation_pb.Discovery
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_config_pb_discovery_proto_depIdxs = []int32{
	2, // 0: kratos_foundation_pb.Discovery.timeout:type_name -> google.protobuf.Duration
	0, // 1: kratos_foundation_pb.Discovery.dc:type_name -> kratos_foundation_pb.DC
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_pb_discovery_proto_init() }
func file_config_pb_discovery_proto_init() {
	if File_config_pb_discovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_pb_discovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Discovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_pb_discovery_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_pb_discovery_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_pb_discovery_proto_goTypes,
		DependencyIndexes: file_config_pb_discovery_proto_depIdxs,
		EnumInfos:         file_config_pb_discovery_proto_enumTypes,
		MessageInfos:      file_config_pb_discovery_proto_msgTypes,
	}.Build()
	File_config_pb_discovery_proto = out.File
	file_config_pb_discovery_proto_rawDesc = nil
	file_config_pb_discovery_proto_goTypes = nil
	file_config_pb_discovery_proto_depIdxs = nil
}
