// Code generated by protoc-gen-kratos-foundation-errors. DO NOT EDIT.

package config_pb

import (
	fmt "fmt"
	errors "github.com/jaggerzhuang1994/kratos-foundation/pkg/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 单数据中心
func IsSingle(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "SINGLE" && e.Metadata != nil && e.Metadata["reason_code"] == "0"
}

// 单数据中心
func ErrorSingle(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "单数据中心"
	}
	return errors.New(500, "SINGLE", fmt.Sprintf(format, args...)).WithReasonCode(0).WithErrStack(4)
}

// 多数据中心
func IsMulti(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "MULTI" && e.Metadata != nil && e.Metadata["reason_code"] == "1"
}

// 多数据中心
func ErrorMulti(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "多数据中心"
	}
	return errors.New(500, "MULTI", fmt.Sprintf(format, args...)).WithReasonCode(1).WithErrStack(4)
}
