// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/job.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Job with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Job) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Job with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in JobMultiError, or nil if none found.
func (m *Job) ValidateAll() error {
	return m.validate(true)
}

func (m *Job) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetJobs()))
		i := 0
		for key := range m.GetJobs() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetJobs()[key]
			_ = val

			// no validation rules for Jobs[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, JobValidationError{
							field:  fmt.Sprintf("Jobs[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, JobValidationError{
							field:  fmt.Sprintf("Jobs[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return JobValidationError{
						field:  fmt.Sprintf("Jobs[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Timezone != nil {
		// no validation rules for Timezone
	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JobValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Tracing != nil {

		if all {
			switch v := interface{}(m.GetTracing()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTracing()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JobValidationError{
					field:  "Tracing",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JobValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JobValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return JobMultiError(errors)
	}

	return nil
}

// JobMultiError is an error wrapping multiple validation errors returned by
// Job.ValidateAll() if the designated constraints aren't met.
type JobMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobMultiError) AllErrors() []error { return m }

// JobValidationError is the validation error returned by Job.Validate if the
// designated constraints aren't met.
type JobValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobValidationError) ErrorName() string { return "JobValidationError" }

// Error satisfies the builtin error interface
func (e JobValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJob.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobValidationError{}

// Validate checks the field values on JobConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JobConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JobConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JobConfigMultiError, or nil
// if none found.
func (m *JobConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *JobConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Schedule

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.ConcurrentPolicy != nil {
		// no validation rules for ConcurrentPolicy
	}

	if m.Immediately != nil {
		// no validation rules for Immediately
	}

	if len(errors) > 0 {
		return JobConfigMultiError(errors)
	}

	return nil
}

// JobConfigMultiError is an error wrapping multiple validation errors returned
// by JobConfig.ValidateAll() if the designated constraints aren't met.
type JobConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobConfigMultiError) AllErrors() []error { return m }

// JobConfigValidationError is the validation error returned by
// JobConfig.Validate if the designated constraints aren't met.
type JobConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobConfigValidationError) ErrorName() string { return "JobConfigValidationError" }

// Error satisfies the builtin error interface
func (e JobConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJobConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobConfigValidationError{}

// Validate checks the field values on Job_Tracing with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Job_Tracing) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Job_Tracing with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Job_TracingMultiError, or
// nil if none found.
func (m *Job_Tracing) ValidateAll() error {
	return m.validate(true)
}

func (m *Job_Tracing) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if len(errors) > 0 {
		return Job_TracingMultiError(errors)
	}

	return nil
}

// Job_TracingMultiError is an error wrapping multiple validation errors
// returned by Job_Tracing.ValidateAll() if the designated constraints aren't met.
type Job_TracingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Job_TracingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Job_TracingMultiError) AllErrors() []error { return m }

// Job_TracingValidationError is the validation error returned by
// Job_Tracing.Validate if the designated constraints aren't met.
type Job_TracingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Job_TracingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Job_TracingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Job_TracingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Job_TracingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Job_TracingValidationError) ErrorName() string { return "Job_TracingValidationError" }

// Error satisfies the builtin error interface
func (e Job_TracingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJob_Tracing.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Job_TracingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Job_TracingValidationError{}

// Validate checks the field values on Job_Metrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Job_Metrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Job_Metrics with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Job_MetricsMultiError, or
// nil if none found.
func (m *Job_Metrics) ValidateAll() error {
	return m.validate(true)
}

func (m *Job_Metrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if len(errors) > 0 {
		return Job_MetricsMultiError(errors)
	}

	return nil
}

// Job_MetricsMultiError is an error wrapping multiple validation errors
// returned by Job_Metrics.ValidateAll() if the designated constraints aren't met.
type Job_MetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Job_MetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Job_MetricsMultiError) AllErrors() []error { return m }

// Job_MetricsValidationError is the validation error returned by
// Job_Metrics.Validate if the designated constraints aren't met.
type Job_MetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Job_MetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Job_MetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Job_MetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Job_MetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Job_MetricsValidationError) ErrorName() string { return "Job_MetricsValidationError" }

// Error satisfies the builtin error interface
func (e Job_MetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJob_Metrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Job_MetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Job_MetricsValidationError{}
