// Code generated by protoc-gen-kratos-foundation-errors. DO NOT EDIT.

package config_pb

import (
	fmt "fmt"
	errors "github.com/jaggerzhuang1994/kratos-foundation/pkg/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 允许重复执行(默认)
func IsOverlap(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "OVERLAP" && e.Metadata != nil && e.Metadata["reason_code"] == "0"
}

// 允许重复执行(默认)
func ErrorOverlap(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "允许重复执行(默认)"
	}
	return errors.New(500, "OVERLAP", fmt.Sprintf(format, args...)).WithReasonCode(0).WithErrStack(4)
}

// 推迟下一个任务
func IsDelay(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "DELAY" && e.Metadata != nil && e.Metadata["reason_code"] == "1"
}

// 推迟下一个任务
func ErrorDelay(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "推迟下一个任务"
	}
	return errors.New(500, "DELAY", fmt.Sprintf(format, args...)).WithReasonCode(1).WithErrStack(4)
}

// 跳过下一个任务
func IsSkip(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "SKIP" && e.Metadata != nil && e.Metadata["reason_code"] == "2"
}

// 跳过下一个任务
func ErrorSkip(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "跳过下一个任务"
	}
	return errors.New(500, "SKIP", fmt.Sprintf(format, args...)).WithReasonCode(2).WithErrStack(4)
}
