// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/kafka.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Kafka with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Kafka) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Kafka with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in KafkaMultiError, or nil if none found.
func (m *Kafka) ValidateAll() error {
	return m.validate(true)
}

func (m *Kafka) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetConnections()))
		i := 0
		for key := range m.GetConnections() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetConnections()[key]
			_ = val

			// no validation rules for Connections[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, KafkaValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, KafkaValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return KafkaValidationError{
						field:  fmt.Sprintf("Connections[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return KafkaMultiError(errors)
	}

	return nil
}

// KafkaMultiError is an error wrapping multiple validation errors returned by
// Kafka.ValidateAll() if the designated constraints aren't met.
type KafkaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaMultiError) AllErrors() []error { return m }

// KafkaValidationError is the validation error returned by Kafka.Validate if
// the designated constraints aren't met.
type KafkaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaValidationError) ErrorName() string { return "KafkaValidationError" }

// Error satisfies the builtin error interface
func (e KafkaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafka.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaValidationError{}

// Validate checks the field values on KafkaConnection with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *KafkaConnection) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaConnection with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// KafkaConnectionMultiError, or nil if none found.
func (m *KafkaConnection) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaConnection) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.ClientId != nil {
		// no validation rules for ClientId
	}

	if m.DialTimeout != nil {

		if all {
			switch v := interface{}(m.GetDialTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "DialTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "DialTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDialTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConnectionValidationError{
					field:  "DialTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.AllowAutoTopicCreation != nil {
		// no validation rules for AllowAutoTopicCreation
	}

	if m.Tls != nil {

		if all {
			switch v := interface{}(m.GetTls()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Tls",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Tls",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTls()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConnectionValidationError{
					field:  "Tls",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Sasl != nil {

		if all {
			switch v := interface{}(m.GetSasl()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Sasl",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Sasl",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSasl()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConnectionValidationError{
					field:  "Sasl",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Producer != nil {

		if all {
			switch v := interface{}(m.GetProducer()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Producer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Producer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetProducer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConnectionValidationError{
					field:  "Producer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Consumer != nil {

		if all {
			switch v := interface{}(m.GetConsumer()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Consumer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConnectionValidationError{
						field:  "Consumer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConsumer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConnectionValidationError{
					field:  "Consumer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return KafkaConnectionMultiError(errors)
	}

	return nil
}

// KafkaConnectionMultiError is an error wrapping multiple validation errors
// returned by KafkaConnection.ValidateAll() if the designated constraints
// aren't met.
type KafkaConnectionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaConnectionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaConnectionMultiError) AllErrors() []error { return m }

// KafkaConnectionValidationError is the validation error returned by
// KafkaConnection.Validate if the designated constraints aren't met.
type KafkaConnectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaConnectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaConnectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaConnectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaConnectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaConnectionValidationError) ErrorName() string { return "KafkaConnectionValidationError" }

// Error satisfies the builtin error interface
func (e KafkaConnectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaConnection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaConnectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaConnectionValidationError{}

// Validate checks the field values on KafkaTLS with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KafkaTLS) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaTLS with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KafkaTLSMultiError, or nil
// if none found.
func (m *KafkaTLS) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaTLS) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.ServerName != nil {
		// no validation rules for ServerName
	}

	if m.InsecureSkipVerify != nil {
		// no validation rules for InsecureSkipVerify
	}

	if m.CaFile != nil {
		// no validation rules for CaFile
	}

	if m.CertFile != nil {
		// no validation rules for CertFile
	}

	if m.KeyFile != nil {
		// no validation rules for KeyFile
	}

	if len(errors) > 0 {
		return KafkaTLSMultiError(errors)
	}

	return nil
}

// KafkaTLSMultiError is an error wrapping multiple validation errors returned
// by KafkaTLS.ValidateAll() if the designated constraints aren't met.
type KafkaTLSMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaTLSMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaTLSMultiError) AllErrors() []error { return m }

// KafkaTLSValidationError is the validation error returned by
// KafkaTLS.Validate if the designated constraints aren't met.
type KafkaTLSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaTLSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaTLSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaTLSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaTLSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaTLSValidationError) ErrorName() string { return "KafkaTLSValidationError" }

// Error satisfies the builtin error interface
func (e KafkaTLSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaTLS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaTLSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaTLSValidationError{}

// Validate checks the field values on KafkaSASL with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KafkaSASL) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaSASL with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KafkaSASLMultiError, or nil
// if none found.
func (m *KafkaSASL) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaSASL) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Mechanism != nil {
		// no validation rules for Mechanism
	}

	if m.Username != nil {
		// no validation rules for Username
	}

	if m.Password != nil {
		// no validation rules for Password
	}

	if len(errors) > 0 {
		return KafkaSASLMultiError(errors)
	}

	return nil
}

// KafkaSASLMultiError is an error wrapping multiple validation errors returned
// by KafkaSASL.ValidateAll() if the designated constraints aren't met.
type KafkaSASLMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaSASLMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaSASLMultiError) AllErrors() []error { return m }

// KafkaSASLValidationError is the validation error returned by
// KafkaSASL.Validate if the designated constraints aren't met.
type KafkaSASLValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaSASLValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaSASLValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaSASLValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaSASLValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaSASLValidationError) ErrorName() string { return "KafkaSASLValidationError" }

// Error satisfies the builtin error interface
func (e KafkaSASLValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaSASL.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaSASLValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaSASLValidationError{}

// Validate checks the field values on KafkaProducer with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KafkaProducer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaProducer with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KafkaProducerMultiError, or
// nil if none found.
func (m *KafkaProducer) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaProducer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.RequiredAcks != nil {
		// no validation rules for RequiredAcks
	}

	if m.Compression != nil {
		// no validation rules for Compression
	}

	if m.Linger != nil {

		if all {
			switch v := interface{}(m.GetLinger()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaProducerValidationError{
						field:  "Linger",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaProducerValidationError{
						field:  "Linger",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLinger()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaProducerValidationError{
					field:  "Linger",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.BatchMaxBytes != nil {
		// no validation rules for BatchMaxBytes
	}

	if len(errors) > 0 {
		return KafkaProducerMultiError(errors)
	}

	return nil
}

// KafkaProducerMultiError is an error wrapping multiple validation errors
// returned by KafkaProducer.ValidateAll() if the designated constraints
// aren't met.
type KafkaProducerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaProducerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaProducerMultiError) AllErrors() []error { return m }

// KafkaProducerValidationError is the validation error returned by
// KafkaProducer.Validate if the designated constraints aren't met.
type KafkaProducerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaProducerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaProducerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaProducerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaProducerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaProducerValidationError) ErrorName() string { return "KafkaProducerValidationError" }

// Error satisfies the builtin error interface
func (e KafkaProducerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaProducer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaProducerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaProducerValidationError{}

// Validate checks the field values on KafkaConsumer with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KafkaConsumer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KafkaConsumer with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KafkaConsumerMultiError, or
// nil if none found.
func (m *KafkaConsumer) ValidateAll() error {
	return m.validate(true)
}

func (m *KafkaConsumer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.SessionTimeout != nil {

		if all {
			switch v := interface{}(m.GetSessionTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "SessionTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "SessionTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSessionTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConsumerValidationError{
					field:  "SessionTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.HeartbeatInterval != nil {

		if all {
			switch v := interface{}(m.GetHeartbeatInterval()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "HeartbeatInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "HeartbeatInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHeartbeatInterval()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConsumerValidationError{
					field:  "HeartbeatInterval",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.RebalanceTimeout != nil {

		if all {
			switch v := interface{}(m.GetRebalanceTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "RebalanceTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "RebalanceTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRebalanceTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConsumerValidationError{
					field:  "RebalanceTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.FetchMinBytes != nil {
		// no validation rules for FetchMinBytes
	}

	if m.FetchMaxBytes != nil {
		// no validation rules for FetchMaxBytes
	}

	if m.FetchMaxWait != nil {

		if all {
			switch v := interface{}(m.GetFetchMaxWait()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "FetchMaxWait",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KafkaConsumerValidationError{
						field:  "FetchMaxWait",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFetchMaxWait()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KafkaConsumerValidationError{
					field:  "FetchMaxWait",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return KafkaConsumerMultiError(errors)
	}

	return nil
}

// KafkaConsumerMultiError is an error wrapping multiple validation errors
// returned by KafkaConsumer.ValidateAll() if the designated constraints
// aren't met.
type KafkaConsumerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KafkaConsumerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KafkaConsumerMultiError) AllErrors() []error { return m }

// KafkaConsumerValidationError is the validation error returned by
// KafkaConsumer.Validate if the designated constraints aren't met.
type KafkaConsumerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KafkaConsumerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KafkaConsumerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KafkaConsumerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KafkaConsumerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KafkaConsumerValidationError) ErrorName() string { return "KafkaConsumerValidationError" }

// Error satisfies the builtin error interface
func (e KafkaConsumerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKafkaConsumer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KafkaConsumerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KafkaConsumerValidationError{}
