// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/log.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Log with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Log) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Log with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LogMultiError, or nil if none found.
func (m *Log) ValidateAll() error {
	return m.validate(true)
}

func (m *Log) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Level != nil {
		// no validation rules for Level
	}

	if m.FilterEmpty != nil {
		// no validation rules for FilterEmpty
	}

	if m.TimeFormat != nil {
		// no validation rules for TimeFormat
	}

	if m.Std != nil {

		if all {
			switch v := interface{}(m.GetStd()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LogValidationError{
						field:  "Std",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LogValidationError{
						field:  "Std",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStd()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LogValidationError{
					field:  "Std",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.File != nil {

		if all {
			switch v := interface{}(m.GetFile()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LogValidationError{
						field:  "File",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LogValidationError{
						field:  "File",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFile()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LogValidationError{
					field:  "File",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return LogMultiError(errors)
	}

	return nil
}

// LogMultiError is an error wrapping multiple validation errors returned by
// Log.ValidateAll() if the designated constraints aren't met.
type LogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogMultiError) AllErrors() []error { return m }

// LogValidationError is the validation error returned by Log.Validate if the
// designated constraints aren't met.
type LogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogValidationError) ErrorName() string { return "LogValidationError" }

// Error satisfies the builtin error interface
func (e LogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogValidationError{}

// Validate checks the field values on StdLogger with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StdLogger) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StdLogger with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StdLoggerMultiError, or nil
// if none found.
func (m *StdLogger) ValidateAll() error {
	return m.validate(true)
}

func (m *StdLogger) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Level != nil {
		// no validation rules for Level
	}

	if len(errors) > 0 {
		return StdLoggerMultiError(errors)
	}

	return nil
}

// StdLoggerMultiError is an error wrapping multiple validation errors returned
// by StdLogger.ValidateAll() if the designated constraints aren't met.
type StdLoggerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StdLoggerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StdLoggerMultiError) AllErrors() []error { return m }

// StdLoggerValidationError is the validation error returned by
// StdLogger.Validate if the designated constraints aren't met.
type StdLoggerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StdLoggerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StdLoggerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StdLoggerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StdLoggerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StdLoggerValidationError) ErrorName() string { return "StdLoggerValidationError" }

// Error satisfies the builtin error interface
func (e StdLoggerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStdLogger.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StdLoggerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StdLoggerValidationError{}

// Validate checks the field values on FileLogger with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileLogger) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileLogger with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileLoggerMultiError, or
// nil if none found.
func (m *FileLogger) ValidateAll() error {
	return m.validate(true)
}

func (m *FileLogger) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Level != nil {
		// no validation rules for Level
	}

	if m.Path != nil {
		// no validation rules for Path
	}

	if m.Rotating != nil {

		if all {
			switch v := interface{}(m.GetRotating()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FileLoggerValidationError{
						field:  "Rotating",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FileLoggerValidationError{
						field:  "Rotating",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRotating()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FileLoggerValidationError{
					field:  "Rotating",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FileLoggerMultiError(errors)
	}

	return nil
}

// FileLoggerMultiError is an error wrapping multiple validation errors
// returned by FileLogger.ValidateAll() if the designated constraints aren't met.
type FileLoggerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileLoggerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileLoggerMultiError) AllErrors() []error { return m }

// FileLoggerValidationError is the validation error returned by
// FileLogger.Validate if the designated constraints aren't met.
type FileLoggerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileLoggerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileLoggerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileLoggerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileLoggerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileLoggerValidationError) ErrorName() string { return "FileLoggerValidationError" }

// Error satisfies the builtin error interface
func (e FileLoggerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileLogger.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileLoggerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileLoggerValidationError{}

// Validate checks the field values on FileRotating with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileRotating) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileRotating with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileRotatingMultiError, or
// nil if none found.
func (m *FileRotating) ValidateAll() error {
	return m.validate(true)
}

func (m *FileRotating) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.MaxSize != nil {
		// no validation rules for MaxSize
	}

	if m.MaxFileAge != nil {
		// no validation rules for MaxFileAge
	}

	if m.MaxFiles != nil {
		// no validation rules for MaxFiles
	}

	if m.LocalTime != nil {
		// no validation rules for LocalTime
	}

	if m.Compress != nil {
		// no validation rules for Compress
	}

	if len(errors) > 0 {
		return FileRotatingMultiError(errors)
	}

	return nil
}

// FileRotatingMultiError is an error wrapping multiple validation errors
// returned by FileRotating.ValidateAll() if the designated constraints aren't met.
type FileRotatingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileRotatingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileRotatingMultiError) AllErrors() []error { return m }

// FileRotatingValidationError is the validation error returned by
// FileRotating.Validate if the designated constraints aren't met.
type FileRotatingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileRotatingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileRotatingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileRotatingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileRotatingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileRotatingValidationError) ErrorName() string { return "FileRotatingValidationError" }

// Error satisfies the builtin error interface
func (e FileRotatingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileRotating.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileRotatingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileRotatingValidationError{}
