// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/metrics.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Metrics with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Metrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Metrics with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MetricsMultiError, or nil if none found.
func (m *Metrics) ValidateAll() error {
	return m.validate(true)
}

func (m *Metrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.MeterName != nil {
		// no validation rules for MeterName
	}

	if m.CounterMapSize != nil {
		// no validation rules for CounterMapSize
	}

	if m.GaugeMapSize != nil {
		// no validation rules for GaugeMapSize
	}

	if m.HistogramMapSize != nil {
		// no validation rules for HistogramMapSize
	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MetricsValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MetricsValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MetricsValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MetricsMultiError(errors)
	}

	return nil
}

// MetricsMultiError is an error wrapping multiple validation errors returned
// by Metrics.ValidateAll() if the designated constraints aren't met.
type MetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MetricsMultiError) AllErrors() []error { return m }

// MetricsValidationError is the validation error returned by Metrics.Validate
// if the designated constraints aren't met.
type MetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetricsValidationError) ErrorName() string { return "MetricsValidationError" }

// Error satisfies the builtin error interface
func (e MetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetricsValidationError{}
