// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/oss.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OSS with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *OSS) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OSS with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OSSMultiError, or nil if none found.
func (m *OSS) ValidateAll() error {
	return m.validate(true)
}

func (m *OSS) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetBuckets()))
		i := 0
		for key := range m.GetBuckets() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetBuckets()[key]
			_ = val

			// no validation rules for Buckets[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, OSSValidationError{
							field:  fmt.Sprintf("Buckets[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, OSSValidationError{
							field:  fmt.Sprintf("Buckets[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return OSSValidationError{
						field:  fmt.Sprintf("Buckets[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return OSSMultiError(errors)
	}

	return nil
}

// OSSMultiError is an error wrapping multiple validation errors returned by
// OSS.ValidateAll() if the designated constraints aren't met.
type OSSMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OSSMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OSSMultiError) AllErrors() []error { return m }

// OSSValidationError is the validation error returned by OSS.Validate if the
// designated constraints aren't met.
type OSSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OSSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OSSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OSSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OSSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OSSValidationError) ErrorName() string { return "OSSValidationError" }

// Error satisfies the builtin error interface
func (e OSSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOSS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OSSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OSSValidationError{}

// Validate checks the field values on OSSBucket with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OSSBucket) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OSSBucket with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OSSBucketMultiError, or nil
// if none found.
func (m *OSSBucket) ValidateAll() error {
	return m.validate(true)
}

func (m *OSSBucket) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Driver

	// no validation rules for Bucket

	// no validation rules for Options

	if m.Domain != nil {
		// no validation rules for Domain
	}

	if len(errors) > 0 {
		return OSSBucketMultiError(errors)
	}

	return nil
}

// OSSBucketMultiError is an error wrapping multiple validation errors returned
// by OSSBucket.ValidateAll() if the designated constraints aren't met.
type OSSBucketMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OSSBucketMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OSSBucketMultiError) AllErrors() []error { return m }

// OSSBucketValidationError is the validation error returned by
// OSSBucket.Validate if the designated constraints aren't met.
type OSSBucketValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OSSBucketValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OSSBucketValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OSSBucketValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OSSBucketValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OSSBucketValidationError) ErrorName() string { return "OSSBucketValidationError" }

// Error satisfies the builtin error interface
func (e OSSBucketValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOSSBucket.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OSSBucketValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OSSBucketValidationError{}
