// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/redis.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Redis with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Redis) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Redis with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RedisMultiError, or nil if none found.
func (m *Redis) ValidateAll() error {
	return m.validate(true)
}

func (m *Redis) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetConnections()))
		i := 0
		for key := range m.GetConnections() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetConnections()[key]
			_ = val

			// no validation rules for Connections[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, RedisValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, RedisValidationError{
							field:  fmt.Sprintf("Connections[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return RedisValidationError{
						field:  fmt.Sprintf("Connections[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.Default != nil {
		// no validation rules for Default
	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Tracing != nil {

		if all {
			switch v := interface{}(m.GetTracing()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTracing()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisValidationError{
					field:  "Tracing",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RedisMultiError(errors)
	}

	return nil
}

// RedisMultiError is an error wrapping multiple validation errors returned by
// Redis.ValidateAll() if the designated constraints aren't met.
type RedisMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedisMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedisMultiError) AllErrors() []error { return m }

// RedisValidationError is the validation error returned by Redis.Validate if
// the designated constraints aren't met.
type RedisValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedisValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedisValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedisValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedisValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedisValidationError) ErrorName() string { return "RedisValidationError" }

// Error satisfies the builtin error interface
func (e RedisValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedis.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedisValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedisValidationError{}

// Validate checks the field values on RedisTracing with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RedisTracing) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedisTracing with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RedisTracingMultiError, or
// nil if none found.
func (m *RedisTracing) ValidateAll() error {
	return m.validate(true)
}

func (m *RedisTracing) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.DbStatement != nil {
		// no validation rules for DbStatement
	}

	if m.CallerEnabled != nil {
		// no validation rules for CallerEnabled
	}

	if m.DialFilter != nil {
		// no validation rules for DialFilter
	}

	if len(errors) > 0 {
		return RedisTracingMultiError(errors)
	}

	return nil
}

// RedisTracingMultiError is an error wrapping multiple validation errors
// returned by RedisTracing.ValidateAll() if the designated constraints aren't met.
type RedisTracingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedisTracingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedisTracingMultiError) AllErrors() []error { return m }

// RedisTracingValidationError is the validation error returned by
// RedisTracing.Validate if the designated constraints aren't met.
type RedisTracingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedisTracingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedisTracingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedisTracingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedisTracingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedisTracingValidationError) ErrorName() string { return "RedisTracingValidationError" }

// Error satisfies the builtin error interface
func (e RedisTracingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedisTracing.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedisTracingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedisTracingValidationError{}

// Validate checks the field values on RedisMetrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RedisMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedisMetrics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RedisMetricsMultiError, or
// nil if none found.
func (m *RedisMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *RedisMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if len(errors) > 0 {
		return RedisMetricsMultiError(errors)
	}

	return nil
}

// RedisMetricsMultiError is an error wrapping multiple validation errors
// returned by RedisMetrics.ValidateAll() if the designated constraints aren't met.
type RedisMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedisMetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedisMetricsMultiError) AllErrors() []error { return m }

// RedisMetricsValidationError is the validation error returned by
// RedisMetrics.Validate if the designated constraints aren't met.
type RedisMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedisMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedisMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedisMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedisMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedisMetricsValidationError) ErrorName() string { return "RedisMetricsValidationError" }

// Error satisfies the builtin error interface
func (e RedisMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedisMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedisMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedisMetricsValidationError{}

// Validate checks the field values on RedisOption with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RedisOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedisOption with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RedisOptionMultiError, or
// nil if none found.
func (m *RedisOption) ValidateAll() error {
	return m.validate(true)
}

func (m *RedisOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Network != nil {
		// no validation rules for Network
	}

	if m.Addr != nil {
		// no validation rules for Addr
	}

	if m.ClientName != nil {
		// no validation rules for ClientName
	}

	if m.Protocol != nil {
		// no validation rules for Protocol
	}

	if m.Username != nil {
		// no validation rules for Username
	}

	if m.Password != nil {
		// no validation rules for Password
	}

	if m.Db != nil {
		// no validation rules for Db
	}

	if m.MaxRetries != nil {
		// no validation rules for MaxRetries
	}

	if m.MinRetryBackoff != nil {

		if all {
			switch v := interface{}(m.GetMinRetryBackoff()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "MinRetryBackoff",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "MinRetryBackoff",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMinRetryBackoff()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "MinRetryBackoff",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.MaxRetryBackoff != nil {

		if all {
			switch v := interface{}(m.GetMaxRetryBackoff()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "MaxRetryBackoff",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "MaxRetryBackoff",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMaxRetryBackoff()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "MaxRetryBackoff",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DialTimeout != nil {

		if all {
			switch v := interface{}(m.GetDialTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "DialTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "DialTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDialTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "DialTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DialerRetries != nil {
		// no validation rules for DialerRetries
	}

	if m.DialerRetryTimeout != nil {

		if all {
			switch v := interface{}(m.GetDialerRetryTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "DialerRetryTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "DialerRetryTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDialerRetryTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "DialerRetryTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ReadTimeout != nil {

		if all {
			switch v := interface{}(m.GetReadTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ReadTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ReadTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetReadTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "ReadTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.WriteTimeout != nil {

		if all {
			switch v := interface{}(m.GetWriteTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "WriteTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "WriteTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetWriteTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "WriteTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ContextTimeoutEnabled != nil {
		// no validation rules for ContextTimeoutEnabled
	}

	if m.ReadBufferSize != nil {
		// no validation rules for ReadBufferSize
	}

	if m.WriteBufferSize != nil {
		// no validation rules for WriteBufferSize
	}

	if m.PoolFifo != nil {
		// no validation rules for PoolFifo
	}

	if m.PoolSize != nil {
		// no validation rules for PoolSize
	}

	if m.MaxConcurrentDials != nil {
		// no validation rules for MaxConcurrentDials
	}

	if m.PoolTimeout != nil {

		if all {
			switch v := interface{}(m.GetPoolTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "PoolTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "PoolTimeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPoolTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "PoolTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.MinIdleConns != nil {
		// no validation rules for MinIdleConns
	}

	if m.MaxIdleConns != nil {
		// no validation rules for MaxIdleConns
	}

	if m.MaxActiveConns != nil {
		// no validation rules for MaxActiveConns
	}

	if m.ConnMaxIdleTime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxIdleTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ConnMaxIdleTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxIdleTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "ConnMaxIdleTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ConnMaxLifetime != nil {

		if all {
			switch v := interface{}(m.GetConnMaxLifetime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedisOptionValidationError{
						field:  "ConnMaxLifetime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetConnMaxLifetime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedisOptionValidationError{
					field:  "ConnMaxLifetime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ReadOnly != nil {
		// no validation rules for ReadOnly
	}

	if m.DisableIndentity != nil {
		// no validation rules for DisableIndentity
	}

	if m.DisableIdentity != nil {
		// no validation rules for DisableIdentity
	}

	if m.IdentitySuffix != nil {
		// no validation rules for IdentitySuffix
	}

	if m.UnstableResp3 != nil {
		// no validation rules for UnstableResp3
	}

	if m.FailingTimeoutSeconds != nil {
		// no validation rules for FailingTimeoutSeconds
	}

	if len(errors) > 0 {
		return RedisOptionMultiError(errors)
	}

	return nil
}

// RedisOptionMultiError is an error wrapping multiple validation errors
// returned by RedisOption.ValidateAll() if the designated constraints aren't met.
type RedisOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedisOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedisOptionMultiError) AllErrors() []error { return m }

// RedisOptionValidationError is the validation error returned by
// RedisOption.Validate if the designated constraints aren't met.
type RedisOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedisOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedisOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedisOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedisOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedisOptionValidationError) ErrorName() string { return "RedisOptionValidationError" }

// Error satisfies the builtin error interface
func (e RedisOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedisOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedisOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedisOptionValidationError{}
