// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/server.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Server with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Server) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Server with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ServerMultiError, or nil if none found.
func (m *Server) ValidateAll() error {
	return m.validate(true)
}

func (m *Server) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.StopDelay != nil {

		if all {
			switch v := interface{}(m.GetStopDelay()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "StopDelay",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "StopDelay",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStopDelay()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerValidationError{
					field:  "StopDelay",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Middleware != nil {

		if all {
			switch v := interface{}(m.GetMiddleware()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Middleware",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Middleware",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMiddleware()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerValidationError{
					field:  "Middleware",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Http != nil {

		if all {
			switch v := interface{}(m.GetHttp()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Http",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Http",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHttp()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerValidationError{
					field:  "Http",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Grpc != nil {

		if all {
			switch v := interface{}(m.GetGrpc()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Grpc",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Grpc",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGrpc()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerValidationError{
					field:  "Grpc",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ServerMultiError(errors)
	}

	return nil
}

// ServerMultiError is an error wrapping multiple validation errors returned by
// Server.ValidateAll() if the designated constraints aren't met.
type ServerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServerMultiError) AllErrors() []error { return m }

// ServerValidationError is the validation error returned by Server.Validate if
// the designated constraints aren't met.
type ServerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerValidationError) ErrorName() string { return "ServerValidationError" }

// Error satisfies the builtin error interface
func (e ServerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerValidationError{}

// Validate checks the field values on ServerMiddleware with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ServerMiddleware) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServerMiddleware with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServerMiddlewareMultiError, or nil if none found.
func (m *ServerMiddleware) ValidateAll() error {
	return m.validate(true)
}

func (m *ServerMiddleware) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Timeout != nil {

		if all {
			switch v := interface{}(m.GetTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metadata != nil {

		if all {
			switch v := interface{}(m.GetMetadata()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Tracing != nil {

		if all {
			switch v := interface{}(m.GetTracing()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Tracing",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTracing()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Tracing",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Logging != nil {

		if all {
			switch v := interface{}(m.GetLogging()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Logging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Logging",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLogging()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Logging",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Validator != nil {

		if all {
			switch v := interface{}(m.GetValidator()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Validator",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "Validator",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetValidator()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "Validator",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.RateLimit != nil {

		if all {
			switch v := interface{}(m.GetRateLimit()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "RateLimit",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServerMiddlewareValidationError{
						field:  "RateLimit",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRateLimit()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServerMiddlewareValidationError{
					field:  "RateLimit",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ServerMiddlewareMultiError(errors)
	}

	return nil
}

// ServerMiddlewareMultiError is an error wrapping multiple validation errors
// returned by ServerMiddleware.ValidateAll() if the designated constraints
// aren't met.
type ServerMiddlewareMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServerMiddlewareMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServerMiddlewareMultiError) AllErrors() []error { return m }

// ServerMiddlewareValidationError is the validation error returned by
// ServerMiddleware.Validate if the designated constraints aren't met.
type ServerMiddlewareValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerMiddlewareValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerMiddlewareValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerMiddlewareValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerMiddlewareValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerMiddlewareValidationError) ErrorName() string { return "ServerMiddlewareValidationError" }

// Error satisfies the builtin error interface
func (e ServerMiddlewareValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerMiddleware.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerMiddlewareValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerMiddlewareValidationError{}

// Validate checks the field values on HttpServerOption with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HttpServerOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HttpServerOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HttpServerOptionMultiError, or nil if none found.
func (m *HttpServerOption) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpServerOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Network != nil {
		// no validation rules for Network
	}

	if m.Addr != nil {
		// no validation rules for Addr
	}

	if m.Endpoint != nil {

		if all {
			switch v := interface{}(m.GetEndpoint()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpServerOptionValidationError{
						field:  "Endpoint",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpServerOptionValidationError{
						field:  "Endpoint",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetEndpoint()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpServerOptionValidationError{
					field:  "Endpoint",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DisableStrictSlash != nil {
		// no validation rules for DisableStrictSlash
	}

	if m.PathPrefix != nil {
		// no validation rules for PathPrefix
	}

	if m.Metrics != nil {

		if all {
			switch v := interface{}(m.GetMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpServerOptionValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpServerOptionValidationError{
						field:  "Metrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpServerOptionValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HttpServerOptionMultiError(errors)
	}

	return nil
}

// HttpServerOptionMultiError is an error wrapping multiple validation errors
// returned by HttpServerOption.ValidateAll() if the designated constraints
// aren't met.
type HttpServerOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpServerOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpServerOptionMultiError) AllErrors() []error { return m }

// HttpServerOptionValidationError is the validation error returned by
// HttpServerOption.Validate if the designated constraints aren't met.
type HttpServerOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpServerOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpServerOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpServerOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpServerOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpServerOptionValidationError) ErrorName() string { return "HttpServerOptionValidationError" }

// Error satisfies the builtin error interface
func (e HttpServerOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpServerOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpServerOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpServerOptionValidationError{}

// Validate checks the field values on GrpcServerOption with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GrpcServerOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrpcServerOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrpcServerOptionMultiError, or nil if none found.
func (m *GrpcServerOption) ValidateAll() error {
	return m.validate(true)
}

func (m *GrpcServerOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Network != nil {
		// no validation rules for Network
	}

	if m.Addr != nil {
		// no validation rules for Addr
	}

	if m.Endpoint != nil {

		if all {
			switch v := interface{}(m.GetEndpoint()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GrpcServerOptionValidationError{
						field:  "Endpoint",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GrpcServerOptionValidationError{
						field:  "Endpoint",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetEndpoint()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GrpcServerOptionValidationError{
					field:  "Endpoint",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.CustomHealth != nil {
		// no validation rules for CustomHealth
	}

	if m.DisableReflection != nil {
		// no validation rules for DisableReflection
	}

	if len(errors) > 0 {
		return GrpcServerOptionMultiError(errors)
	}

	return nil
}

// GrpcServerOptionMultiError is an error wrapping multiple validation errors
// returned by GrpcServerOption.ValidateAll() if the designated constraints
// aren't met.
type GrpcServerOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrpcServerOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrpcServerOptionMultiError) AllErrors() []error { return m }

// GrpcServerOptionValidationError is the validation error returned by
// GrpcServerOption.Validate if the designated constraints aren't met.
type GrpcServerOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrpcServerOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrpcServerOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrpcServerOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrpcServerOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrpcServerOptionValidationError) ErrorName() string { return "GrpcServerOptionValidationError" }

// Error satisfies the builtin error interface
func (e GrpcServerOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrpcServerOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrpcServerOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrpcServerOptionValidationError{}

// Validate checks the field values on HttpServerOption_Metrics with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HttpServerOption_Metrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HttpServerOption_Metrics with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HttpServerOption_MetricsMultiError, or nil if none found.
func (m *HttpServerOption_Metrics) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpServerOption_Metrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.Path != nil {
		// no validation rules for Path
	}

	if len(errors) > 0 {
		return HttpServerOption_MetricsMultiError(errors)
	}

	return nil
}

// HttpServerOption_MetricsMultiError is an error wrapping multiple validation
// errors returned by HttpServerOption_Metrics.ValidateAll() if the designated
// constraints aren't met.
type HttpServerOption_MetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpServerOption_MetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpServerOption_MetricsMultiError) AllErrors() []error { return m }

// HttpServerOption_MetricsValidationError is the validation error returned by
// HttpServerOption_Metrics.Validate if the designated constraints aren't met.
type HttpServerOption_MetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpServerOption_MetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpServerOption_MetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpServerOption_MetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpServerOption_MetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpServerOption_MetricsValidationError) ErrorName() string {
	return "HttpServerOption_MetricsValidationError"
}

// Error satisfies the builtin error interface
func (e HttpServerOption_MetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpServerOption_Metrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpServerOption_MetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpServerOption_MetricsValidationError{}
