// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config_pb/tracing.proto

package config_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Tracing with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Tracing) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tracing with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TracingMultiError, or nil if none found.
func (m *Tracing) ValidateAll() error {
	return m.validate(true)
}

func (m *Tracing) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Disable != nil {
		// no validation rules for Disable
	}

	if m.TracerName != nil {
		// no validation rules for TracerName
	}

	if m.Exporter != nil {

		if all {
			switch v := interface{}(m.GetExporter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Exporter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Exporter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetExporter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TracingValidationError{
					field:  "Exporter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Sampler != nil {

		if all {
			switch v := interface{}(m.GetSampler()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Sampler",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Sampler",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSampler()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TracingValidationError{
					field:  "Sampler",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Log != nil {

		if all {
			switch v := interface{}(m.GetLog()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TracingValidationError{
						field:  "Log",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLog()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TracingValidationError{
					field:  "Log",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TracingMultiError(errors)
	}

	return nil
}

// TracingMultiError is an error wrapping multiple validation errors returned
// by Tracing.ValidateAll() if the designated constraints aren't met.
type TracingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TracingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TracingMultiError) AllErrors() []error { return m }

// TracingValidationError is the validation error returned by Tracing.Validate
// if the designated constraints aren't met.
type TracingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TracingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TracingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TracingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TracingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TracingValidationError) ErrorName() string { return "TracingValidationError" }

// Error satisfies the builtin error interface
func (e TracingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTracing.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TracingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TracingValidationError{}

// Validate checks the field values on Exporter with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Exporter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Exporter with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExporterMultiError, or nil
// if none found.
func (m *Exporter) ValidateAll() error {
	return m.validate(true)
}

func (m *Exporter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Headers

	if m.EndpointUrl != nil {
		// no validation rules for EndpointUrl
	}

	if m.Compression != nil {
		// no validation rules for Compression
	}

	if m.Timeout != nil {

		if all {
			switch v := interface{}(m.GetTimeout()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExporterValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExporterValidationError{
						field:  "Timeout",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimeout()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExporterValidationError{
					field:  "Timeout",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Retry != nil {

		if all {
			switch v := interface{}(m.GetRetry()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExporterValidationError{
						field:  "Retry",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExporterValidationError{
						field:  "Retry",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRetry()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExporterValidationError{
					field:  "Retry",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ExporterMultiError(errors)
	}

	return nil
}

// ExporterMultiError is an error wrapping multiple validation errors returned
// by Exporter.ValidateAll() if the designated constraints aren't met.
type ExporterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExporterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExporterMultiError) AllErrors() []error { return m }

// ExporterValidationError is the validation error returned by
// Exporter.Validate if the designated constraints aren't met.
type ExporterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExporterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExporterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExporterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExporterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExporterValidationError) ErrorName() string { return "ExporterValidationError" }

// Error satisfies the builtin error interface
func (e ExporterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExporter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExporterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExporterValidationError{}

// Validate checks the field values on Sampler with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Sampler) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sampler with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SamplerMultiError, or nil if none found.
func (m *Sampler) ValidateAll() error {
	return m.validate(true)
}

func (m *Sampler) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Sample != nil {
		// no validation rules for Sample
	}

	if m.Ratio != nil {
		// no validation rules for Ratio
	}

	if len(errors) > 0 {
		return SamplerMultiError(errors)
	}

	return nil
}

// SamplerMultiError is an error wrapping multiple validation errors returned
// by Sampler.ValidateAll() if the designated constraints aren't met.
type SamplerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SamplerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SamplerMultiError) AllErrors() []error { return m }

// SamplerValidationError is the validation error returned by Sampler.Validate
// if the designated constraints aren't met.
type SamplerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SamplerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SamplerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SamplerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SamplerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SamplerValidationError) ErrorName() string { return "SamplerValidationError" }

// Error satisfies the builtin error interface
func (e SamplerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSampler.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SamplerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SamplerValidationError{}

// Validate checks the field values on Exporter_RetryConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Exporter_RetryConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Exporter_RetryConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Exporter_RetryConfigMultiError, or nil if none found.
func (m *Exporter_RetryConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *Exporter_RetryConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Enabled != nil {
		// no validation rules for Enabled
	}

	if m.InitialInterval != nil {

		if all {
			switch v := interface{}(m.GetInitialInterval()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "InitialInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "InitialInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetInitialInterval()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Exporter_RetryConfigValidationError{
					field:  "InitialInterval",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.MaxInterval != nil {

		if all {
			switch v := interface{}(m.GetMaxInterval()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "MaxInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "MaxInterval",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMaxInterval()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Exporter_RetryConfigValidationError{
					field:  "MaxInterval",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.MaxElapsedTime != nil {

		if all {
			switch v := interface{}(m.GetMaxElapsedTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "MaxElapsedTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Exporter_RetryConfigValidationError{
						field:  "MaxElapsedTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMaxElapsedTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Exporter_RetryConfigValidationError{
					field:  "MaxElapsedTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Exporter_RetryConfigMultiError(errors)
	}

	return nil
}

// Exporter_RetryConfigMultiError is an error wrapping multiple validation
// errors returned by Exporter_RetryConfig.ValidateAll() if the designated
// constraints aren't met.
type Exporter_RetryConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Exporter_RetryConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Exporter_RetryConfigMultiError) AllErrors() []error { return m }

// Exporter_RetryConfigValidationError is the validation error returned by
// Exporter_RetryConfig.Validate if the designated constraints aren't met.
type Exporter_RetryConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Exporter_RetryConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Exporter_RetryConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Exporter_RetryConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Exporter_RetryConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Exporter_RetryConfigValidationError) ErrorName() string {
	return "Exporter_RetryConfigValidationError"
}

// Error satisfies the builtin error interface
func (e Exporter_RetryConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExporter_RetryConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Exporter_RetryConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Exporter_RetryConfigValidationError{}
