// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: error_reason.proto

package kratos_foundation_pb

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason
type ErrorReason int32

const (
	// undefined
	ErrorReason_UNDEFINED ErrorReason = 0
	// 部分失败
	ErrorReason_PARTIAL_ERROR       ErrorReason = 206
	ErrorReason_BAD_REQUEST         ErrorReason = 400 // 异常请求
	ErrorReason_UNAUTHORIZED        ErrorReason = 401 // 无效身份
	ErrorReason_FORBIDDEN           ErrorReason = 403 // 无权限操作
	ErrorReason_NOT_FOUND           ErrorReason = 404 // 数据不存在
	ErrorReason_CONFLICT            ErrorReason = 409 // 请求冲突
	ErrorReason_VALIDATOR           ErrorReason = 422 // 请求字段校验失败
	ErrorReason_TOO_MANY_REQUESTS   ErrorReason = 429 // 请求次数过多
	ErrorReason_CLIENT_DISCONNECTED ErrorReason = 499 // client has closed connection
	ErrorReason_INTERNAL_SERVER     ErrorReason = 500 // 服务器错误
	ErrorReason_SERVICE_UNAVAILABLE ErrorReason = 503 // 服务不可用
	ErrorReason_GATEWAY_TIMEOUT     ErrorReason = 504 // 网关超时
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "UNDEFINED",
		206: "PARTIAL_ERROR",
		400: "BAD_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		409: "CONFLICT",
		422: "VALIDATOR",
		429: "TOO_MANY_REQUESTS",
		499: "CLIENT_DISCONNECTED",
		500: "INTERNAL_SERVER",
		503: "SERVICE_UNAVAILABLE",
		504: "GATEWAY_TIMEOUT",
	}
	ErrorReason_value = map[string]int32{
		"UNDEFINED":           0,
		"PARTIAL_ERROR":       206,
		"BAD_REQUEST":         400,
		"UNAUTHORIZED":        401,
		"FORBIDDEN":           403,
		"NOT_FOUND":           404,
		"CONFLICT":            409,
		"VALIDATOR":           422,
		"TOO_MANY_REQUESTS":   429,
		"CLIENT_DISCONNECTED": 499,
		"INTERNAL_SERVER":     500,
		"SERVICE_UNAVAILABLE": 503,
		"GATEWAY_TIMEOUT":     504,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_error_reason_proto protoreflect.FileDescriptor

const file_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x12error_reason.proto\x12\x14kratos_foundation_pb\x1a\x13errors/errors.proto*\xe0\x02\n" +
	"\vErrorReason\x12\x13\n" +
	"\tUNDEFINED\x10\x00\x1a\x04\xa8E\xc8\x01\x12\x18\n" +
	"\rPARTIAL_ERROR\x10\xce\x01\x1a\x04\xa8E\xce\x01\x12\x16\n" +
	"\vBAD_REQUEST\x10\x90\x03\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x1a\x04\xa8E\x91\x03\x12\x14\n" +
	"\tFORBIDDEN\x10\x93\x03\x1a\x04\xa8E\x93\x03\x12\x14\n" +
	"\tNOT_FOUND\x10\x94\x03\x1a\x04\xa8E\x94\x03\x12\x13\n" +
	"\bCONFLICT\x10\x99\x03\x1a\x04\xa8E\x99\x03\x12\x14\n" +
	"\tVALIDATOR\x10\xa6\x03\x1a\x04\xa8E\xa6\x03\x12\x1c\n" +
	"\x11TOO_MANY_REQUESTS\x10\xad\x03\x1a\x04\xa8E\xad\x03\x12\x1e\n" +
	"\x13CLIENT_DISCONNECTED\x10\xf3\x03\x1a\x04\xa8E\xf3\x03\x12\x1a\n" +
	"\x0fINTERNAL_SERVER\x10\xf4\x03\x1a\x04\xa8E\xf4\x03\x12\x1e\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x03\x1a\x04\xa8E\xf7\x03\x12\x1a\n" +
	"\x0fGATEWAY_TIMEOUT\x10\xf8\x03\x1a\x04\xa8E\xf8\x03\x1a\x04\xa0E\xf4\x03BJZHgithub.com/jaggerzhuang1994/kratos-foundation/proto/kratos_foundation_pbb\x06proto3"

var (
	file_error_reason_proto_rawDescOnce sync.Once
	file_error_reason_proto_rawDescData []byte
)

func file_error_reason_proto_rawDescGZIP() []byte {
	file_error_reason_proto_rawDescOnce.Do(func() {
		file_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)))
	})
	return file_error_reason_proto_rawDescData
}

var file_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: kratos_foundation_pb.ErrorReason
}
var file_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_reason_proto_init() }
func file_error_reason_proto_init() {
	if File_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_reason_proto_goTypes,
		DependencyIndexes: file_error_reason_proto_depIdxs,
		EnumInfos:         file_error_reason_proto_enumTypes,
	}.Build()
	File_error_reason_proto = out.File
	file_error_reason_proto_goTypes = nil
	file_error_reason_proto_depIdxs = nil
}
