// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/app"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/appinfo"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/bootstrap"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/config"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/job"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/log"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/metrics"
	"github.com/jaggerzhuang1994/kratos-foundation/v2/pkg/tracing"
)

// Injectors from wire.go:

func initialize(path configPath, version2 string) (*kratos.App, func(), error) {
	spec := bootstrap.NewSpec()
	appSpec := bootstrap.ApplicationSpec(spec)
	appInfo := appinfo.New(version2)
	appInfoBootstrap, err := bootstrap.NewAppInfoBootstrap(appInfo, appSpec)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := log.NewLogger()
	if err != nil {
		return nil, nil, err
	}
	logBootstrap, cleanup2, err := bootstrap.NewLogBootstrap(logger, appSpec)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracingBootstrap, err := bootstrap.NewTracingBootstrap()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	provider, cleanup3, err := metrics.NewProvider(appInfo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := metrics.NewMetrics(provider, appInfo)
	metricsBootstrap, err := bootstrap.NewMetricsBootstrap(appSpec, v)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sources, err := newSources(path)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager, cleanup4, err := config.NewManager(sources)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configObservabilityBootstrap, cleanup5, err := bootstrap.NewConfigObservabilityBootstrap(manager, provider)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	infrastructureBootstrap := bootstrap.NewInfrastructureBootstrap(appInfoBootstrap, logBootstrap, tracingBootstrap, metricsBootstrap, configObservabilityBootstrap)
	tracingProvider, cleanup6, err := tracing.NewProvider(manager, appInfo)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainGreetingService, err := newGreetingService(provider)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bootstrapBootstrap, err := boot(infrastructureBootstrap, spec, mainGreetingService)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	concurrencyCoordinator := job.DefaultCoordinator()
	componentsBootstrap, cleanup7, err := bootstrap.NewComponentsBootstrap(spec, manager, logger, provider, tracingProvider, bootstrapBootstrap, concurrencyCoordinator)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	startupReady := bootstrap.NewApplicationBootstrap(infrastructureBootstrap, componentsBootstrap)
	v2, err := app.NewConfig(manager)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stopPolicy, cleanup8, err := bootstrap.NewStopPolicy(v2, manager, logger, componentsBootstrap)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registrar := newRegistrar()
	kratosApp, err := bootstrap.NewKratosApp(appSpec, startupReady, v2, stopPolicy, registrar)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return kratosApp, func() {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
