// Code generated by gen_default_client.go; DO NOT EDIT.
package redis

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/redis/go-redis/v9/maintnotifications"
	"github.com/redis/go-redis/v9/push"
)

func (m *Manager) ACLCat(arg0 context.Context) *redis.StringSliceCmd {
	return m.defaultConn.ACLCat(arg0)
}

func (m *Manager) ACLCatArgs(arg0 context.Context, arg1 *redis.ACLCatArgs) *redis.StringSliceCmd {
	return m.defaultConn.ACLCatArgs(arg0, arg1)
}

func (m *Manager) ACLDelUser(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ACLDelUser(arg0, arg1)
}

func (m *Manager) ACLDryRun(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.StringCmd {
	return m.defaultConn.ACLDryRun(arg0, arg1, arg2...)
}

func (m *Manager) ACLGenPass(arg0 context.Context, arg1 int) *redis.StringCmd {
	return m.defaultConn.ACLGenPass(arg0, arg1)
}

func (m *Manager) ACLList(arg0 context.Context) *redis.StringSliceCmd {
	return m.defaultConn.ACLList(arg0)
}

func (m *Manager) ACLLog(arg0 context.Context, arg1 int64) *redis.ACLLogCmd {
	return m.defaultConn.ACLLog(arg0, arg1)
}

func (m *Manager) ACLLogReset(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ACLLogReset(arg0)
}

func (m *Manager) ACLSetUser(arg0 context.Context, arg1 string, arg2 ...string) *redis.StatusCmd {
	return m.defaultConn.ACLSetUser(arg0, arg1, arg2...)
}

func (m *Manager) ACLUsers(arg0 context.Context) *redis.StringSliceCmd {
	return m.defaultConn.ACLUsers(arg0)
}

func (m *Manager) ACLWhoAmI(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ACLWhoAmI(arg0)
}

func (m *Manager) AddHook(arg0 redis.Hook) {
	m.defaultConn.AddHook(arg0)
}

func (m *Manager) Append(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.Append(arg0, arg1, arg2)
}

func (m *Manager) BFAdd(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.BFAdd(arg0, arg1, arg2)
}

func (m *Manager) BFCard(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.BFCard(arg0, arg1)
}

func (m *Manager) BFExists(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.BFExists(arg0, arg1, arg2)
}

func (m *Manager) BFInfo(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfo(arg0, arg1)
}

func (m *Manager) BFInfoArg(arg0 context.Context, arg1 string, arg2 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoArg(arg0, arg1, arg2)
}

func (m *Manager) BFInfoCapacity(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoCapacity(arg0, arg1)
}

func (m *Manager) BFInfoExpansion(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoExpansion(arg0, arg1)
}

func (m *Manager) BFInfoFilters(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoFilters(arg0, arg1)
}

func (m *Manager) BFInfoItems(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoItems(arg0, arg1)
}

func (m *Manager) BFInfoSize(arg0 context.Context, arg1 string) *redis.BFInfoCmd {
	return m.defaultConn.BFInfoSize(arg0, arg1)
}

func (m *Manager) BFInsert(arg0 context.Context, arg1 string, arg2 *redis.BFInsertOptions, arg3 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.BFInsert(arg0, arg1, arg2, arg3...)
}

func (m *Manager) BFLoadChunk(arg0 context.Context, arg1 string, arg2 int64, arg3 interface{}) *redis.StatusCmd {
	return m.defaultConn.BFLoadChunk(arg0, arg1, arg2, arg3)
}

func (m *Manager) BFMAdd(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.BFMAdd(arg0, arg1, arg2...)
}

func (m *Manager) BFMExists(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.BFMExists(arg0, arg1, arg2...)
}

func (m *Manager) BFReserve(arg0 context.Context, arg1 string, arg2 float64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.BFReserve(arg0, arg1, arg2, arg3)
}

func (m *Manager) BFReserveExpansion(arg0 context.Context, arg1 string, arg2 float64, arg3 int64, arg4 int64) *redis.StatusCmd {
	return m.defaultConn.BFReserveExpansion(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) BFReserveNonScaling(arg0 context.Context, arg1 string, arg2 float64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.BFReserveNonScaling(arg0, arg1, arg2, arg3)
}

func (m *Manager) BFReserveWithArgs(arg0 context.Context, arg1 string, arg2 *redis.BFReserveOptions) *redis.StatusCmd {
	return m.defaultConn.BFReserveWithArgs(arg0, arg1, arg2)
}

func (m *Manager) BFScanDump(arg0 context.Context, arg1 string, arg2 int64) *redis.ScanDumpCmd {
	return m.defaultConn.BFScanDump(arg0, arg1, arg2)
}

func (m *Manager) BLMPop(arg0 context.Context, arg1 time.Duration, arg2 string, arg3 int64, arg4 ...string) *redis.KeyValuesCmd {
	return m.defaultConn.BLMPop(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) BLMove(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 string, arg5 time.Duration) *redis.StringCmd {
	return m.defaultConn.BLMove(arg0, arg1, arg2, arg3, arg4, arg5)
}

func (m *Manager) BLPop(arg0 context.Context, arg1 time.Duration, arg2 ...string) *redis.StringSliceCmd {
	return m.defaultConn.BLPop(arg0, arg1, arg2...)
}

func (m *Manager) BRPop(arg0 context.Context, arg1 time.Duration, arg2 ...string) *redis.StringSliceCmd {
	return m.defaultConn.BRPop(arg0, arg1, arg2...)
}

func (m *Manager) BRPopLPush(arg0 context.Context, arg1 string, arg2 string, arg3 time.Duration) *redis.StringCmd {
	return m.defaultConn.BRPopLPush(arg0, arg1, arg2, arg3)
}

func (m *Manager) BZMPop(arg0 context.Context, arg1 time.Duration, arg2 string, arg3 int64, arg4 ...string) *redis.ZSliceWithKeyCmd {
	return m.defaultConn.BZMPop(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) BZPopMax(arg0 context.Context, arg1 time.Duration, arg2 ...string) *redis.ZWithKeyCmd {
	return m.defaultConn.BZPopMax(arg0, arg1, arg2...)
}

func (m *Manager) BZPopMin(arg0 context.Context, arg1 time.Duration, arg2 ...string) *redis.ZWithKeyCmd {
	return m.defaultConn.BZPopMin(arg0, arg1, arg2...)
}

func (m *Manager) BgRewriteAOF(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.BgRewriteAOF(arg0)
}

func (m *Manager) BgSave(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.BgSave(arg0)
}

func (m *Manager) BitCount(arg0 context.Context, arg1 string, arg2 *redis.BitCount) *redis.IntCmd {
	return m.defaultConn.BitCount(arg0, arg1, arg2)
}

func (m *Manager) BitField(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.BitField(arg0, arg1, arg2...)
}

func (m *Manager) BitFieldRO(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.BitFieldRO(arg0, arg1, arg2...)
}

func (m *Manager) BitOpAnd(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpAnd(arg0, arg1, arg2...)
}

func (m *Manager) BitOpAndOr(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpAndOr(arg0, arg1, arg2...)
}

func (m *Manager) BitOpDiff(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpDiff(arg0, arg1, arg2...)
}

func (m *Manager) BitOpDiff1(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpDiff1(arg0, arg1, arg2...)
}

func (m *Manager) BitOpNot(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.BitOpNot(arg0, arg1, arg2)
}

func (m *Manager) BitOpOne(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpOne(arg0, arg1, arg2...)
}

func (m *Manager) BitOpOr(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpOr(arg0, arg1, arg2...)
}

func (m *Manager) BitOpXor(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.BitOpXor(arg0, arg1, arg2...)
}

func (m *Manager) BitPos(arg0 context.Context, arg1 string, arg2 int64, arg3 ...int64) *redis.IntCmd {
	return m.defaultConn.BitPos(arg0, arg1, arg2, arg3...)
}

func (m *Manager) BitPosSpan(arg0 context.Context, arg1 string, arg2 int8, arg3 int64, arg4 int64, arg5 string) *redis.IntCmd {
	return m.defaultConn.BitPosSpan(arg0, arg1, arg2, arg3, arg4, arg5)
}

func (m *Manager) CFAdd(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.CFAdd(arg0, arg1, arg2)
}

func (m *Manager) CFAddNX(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.CFAddNX(arg0, arg1, arg2)
}

func (m *Manager) CFCount(arg0 context.Context, arg1 string, arg2 interface{}) *redis.IntCmd {
	return m.defaultConn.CFCount(arg0, arg1, arg2)
}

func (m *Manager) CFDel(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.CFDel(arg0, arg1, arg2)
}

func (m *Manager) CFExists(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.CFExists(arg0, arg1, arg2)
}

func (m *Manager) CFInfo(arg0 context.Context, arg1 string) *redis.CFInfoCmd {
	return m.defaultConn.CFInfo(arg0, arg1)
}

func (m *Manager) CFInsert(arg0 context.Context, arg1 string, arg2 *redis.CFInsertOptions, arg3 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.CFInsert(arg0, arg1, arg2, arg3...)
}

func (m *Manager) CFInsertNX(arg0 context.Context, arg1 string, arg2 *redis.CFInsertOptions, arg3 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.CFInsertNX(arg0, arg1, arg2, arg3...)
}

func (m *Manager) CFLoadChunk(arg0 context.Context, arg1 string, arg2 int64, arg3 interface{}) *redis.StatusCmd {
	return m.defaultConn.CFLoadChunk(arg0, arg1, arg2, arg3)
}

func (m *Manager) CFMExists(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.CFMExists(arg0, arg1, arg2...)
}

func (m *Manager) CFReserve(arg0 context.Context, arg1 string, arg2 int64) *redis.StatusCmd {
	return m.defaultConn.CFReserve(arg0, arg1, arg2)
}

func (m *Manager) CFReserveBucketSize(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.CFReserveBucketSize(arg0, arg1, arg2, arg3)
}

func (m *Manager) CFReserveExpansion(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.CFReserveExpansion(arg0, arg1, arg2, arg3)
}

func (m *Manager) CFReserveMaxIterations(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.CFReserveMaxIterations(arg0, arg1, arg2, arg3)
}

func (m *Manager) CFReserveWithArgs(arg0 context.Context, arg1 string, arg2 *redis.CFReserveOptions) *redis.StatusCmd {
	return m.defaultConn.CFReserveWithArgs(arg0, arg1, arg2)
}

func (m *Manager) CFScanDump(arg0 context.Context, arg1 string, arg2 int64) *redis.ScanDumpCmd {
	return m.defaultConn.CFScanDump(arg0, arg1, arg2)
}

func (m *Manager) CMSIncrBy(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.CMSIncrBy(arg0, arg1, arg2...)
}

func (m *Manager) CMSInfo(arg0 context.Context, arg1 string) *redis.CMSInfoCmd {
	return m.defaultConn.CMSInfo(arg0, arg1)
}

func (m *Manager) CMSInitByDim(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.CMSInitByDim(arg0, arg1, arg2, arg3)
}

func (m *Manager) CMSInitByProb(arg0 context.Context, arg1 string, arg2 float64, arg3 float64) *redis.StatusCmd {
	return m.defaultConn.CMSInitByProb(arg0, arg1, arg2, arg3)
}

func (m *Manager) CMSMerge(arg0 context.Context, arg1 string, arg2 ...string) *redis.StatusCmd {
	return m.defaultConn.CMSMerge(arg0, arg1, arg2...)
}

func (m *Manager) CMSMergeWithWeight(arg0 context.Context, arg1 string, arg2 map[string]int64) *redis.StatusCmd {
	return m.defaultConn.CMSMergeWithWeight(arg0, arg1, arg2)
}

func (m *Manager) CMSQuery(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.CMSQuery(arg0, arg1, arg2...)
}

func (m *Manager) ClientGetName(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClientGetName(arg0)
}

func (m *Manager) ClientID(arg0 context.Context) *redis.IntCmd {
	return m.defaultConn.ClientID(arg0)
}

func (m *Manager) ClientInfo(arg0 context.Context) *redis.ClientInfoCmd {
	return m.defaultConn.ClientInfo(arg0)
}

func (m *Manager) ClientKill(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.ClientKill(arg0, arg1)
}

func (m *Manager) ClientKillByFilter(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.ClientKillByFilter(arg0, arg1...)
}

func (m *Manager) ClientList(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClientList(arg0)
}

func (m *Manager) ClientMaintNotifications(arg0 context.Context, arg1 bool, arg2 string) *redis.StatusCmd {
	return m.defaultConn.ClientMaintNotifications(arg0, arg1, arg2)
}

func (m *Manager) ClientPause(arg0 context.Context, arg1 time.Duration) *redis.BoolCmd {
	return m.defaultConn.ClientPause(arg0, arg1)
}

func (m *Manager) ClientUnblock(arg0 context.Context, arg1 int64) *redis.IntCmd {
	return m.defaultConn.ClientUnblock(arg0, arg1)
}

func (m *Manager) ClientUnblockWithError(arg0 context.Context, arg1 int64) *redis.IntCmd {
	return m.defaultConn.ClientUnblockWithError(arg0, arg1)
}

func (m *Manager) ClientUnpause(arg0 context.Context) *redis.BoolCmd {
	return m.defaultConn.ClientUnpause(arg0)
}

func (m *Manager) Close() error {
	return m.defaultConn.Close()
}

func (m *Manager) ClusterAddSlots(arg0 context.Context, arg1 ...int) *redis.StatusCmd {
	return m.defaultConn.ClusterAddSlots(arg0, arg1...)
}

func (m *Manager) ClusterAddSlotsRange(arg0 context.Context, arg1 int, arg2 int) *redis.StatusCmd {
	return m.defaultConn.ClusterAddSlotsRange(arg0, arg1, arg2)
}

func (m *Manager) ClusterCountFailureReports(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ClusterCountFailureReports(arg0, arg1)
}

func (m *Manager) ClusterCountKeysInSlot(arg0 context.Context, arg1 int) *redis.IntCmd {
	return m.defaultConn.ClusterCountKeysInSlot(arg0, arg1)
}

func (m *Manager) ClusterDelSlots(arg0 context.Context, arg1 ...int) *redis.StatusCmd {
	return m.defaultConn.ClusterDelSlots(arg0, arg1...)
}

func (m *Manager) ClusterDelSlotsRange(arg0 context.Context, arg1 int, arg2 int) *redis.StatusCmd {
	return m.defaultConn.ClusterDelSlotsRange(arg0, arg1, arg2)
}

func (m *Manager) ClusterFailover(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ClusterFailover(arg0)
}

func (m *Manager) ClusterForget(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.ClusterForget(arg0, arg1)
}

func (m *Manager) ClusterGetKeysInSlot(arg0 context.Context, arg1 int, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.ClusterGetKeysInSlot(arg0, arg1, arg2)
}

func (m *Manager) ClusterInfo(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClusterInfo(arg0)
}

func (m *Manager) ClusterKeySlot(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ClusterKeySlot(arg0, arg1)
}

func (m *Manager) ClusterLinks(arg0 context.Context) *redis.ClusterLinksCmd {
	return m.defaultConn.ClusterLinks(arg0)
}

func (m *Manager) ClusterMeet(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.ClusterMeet(arg0, arg1, arg2)
}

func (m *Manager) ClusterMyID(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClusterMyID(arg0)
}

func (m *Manager) ClusterMyShardID(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClusterMyShardID(arg0)
}

func (m *Manager) ClusterNodes(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.ClusterNodes(arg0)
}

func (m *Manager) ClusterReplicate(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.ClusterReplicate(arg0, arg1)
}

func (m *Manager) ClusterResetHard(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ClusterResetHard(arg0)
}

func (m *Manager) ClusterResetSoft(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ClusterResetSoft(arg0)
}

func (m *Manager) ClusterSaveConfig(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ClusterSaveConfig(arg0)
}

func (m *Manager) ClusterShards(arg0 context.Context) *redis.ClusterShardsCmd {
	return m.defaultConn.ClusterShards(arg0)
}

func (m *Manager) ClusterSlaves(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.ClusterSlaves(arg0, arg1)
}

func (m *Manager) ClusterSlots(arg0 context.Context) *redis.ClusterSlotsCmd {
	return m.defaultConn.ClusterSlots(arg0)
}

func (m *Manager) Command(arg0 context.Context) *redis.CommandsInfoCmd {
	return m.defaultConn.Command(arg0)
}

func (m *Manager) CommandGetKeys(arg0 context.Context, arg1 ...interface{}) *redis.StringSliceCmd {
	return m.defaultConn.CommandGetKeys(arg0, arg1...)
}

func (m *Manager) CommandGetKeysAndFlags(arg0 context.Context, arg1 ...interface{}) *redis.KeyFlagsCmd {
	return m.defaultConn.CommandGetKeysAndFlags(arg0, arg1...)
}

func (m *Manager) CommandList(arg0 context.Context, arg1 *redis.FilterBy) *redis.StringSliceCmd {
	return m.defaultConn.CommandList(arg0, arg1)
}

func (m *Manager) ConfigGet(arg0 context.Context, arg1 string) *redis.MapStringStringCmd {
	return m.defaultConn.ConfigGet(arg0, arg1)
}

func (m *Manager) ConfigResetStat(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ConfigResetStat(arg0)
}

func (m *Manager) ConfigRewrite(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ConfigRewrite(arg0)
}

func (m *Manager) ConfigSet(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.ConfigSet(arg0, arg1, arg2)
}

func (m *Manager) Conn() *redis.Conn {
	return m.defaultConn.Conn()
}

func (m *Manager) Copy(arg0 context.Context, arg1 string, arg2 string, arg3 int, arg4 bool) *redis.IntCmd {
	return m.defaultConn.Copy(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) DBSize(arg0 context.Context) *redis.IntCmd {
	return m.defaultConn.DBSize(arg0)
}

func (m *Manager) DebugObject(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.DebugObject(arg0, arg1)
}

func (m *Manager) Decr(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.Decr(arg0, arg1)
}

func (m *Manager) DecrBy(arg0 context.Context, arg1 string, arg2 int64) *redis.IntCmd {
	return m.defaultConn.DecrBy(arg0, arg1, arg2)
}

func (m *Manager) Del(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.Del(arg0, arg1...)
}

func (m *Manager) DelExArgs(arg0 context.Context, arg1 string, arg2 redis.DelExArgs) *redis.IntCmd {
	return m.defaultConn.DelExArgs(arg0, arg1, arg2)
}

func (m *Manager) Digest(arg0 context.Context, arg1 string) *redis.DigestCmd {
	return m.defaultConn.Digest(arg0, arg1)
}

func (m *Manager) Do(arg0 context.Context, arg1 ...interface{}) *redis.Cmd {
	return m.defaultConn.Do(arg0, arg1...)
}

func (m *Manager) Dump(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.Dump(arg0, arg1)
}

func (m *Manager) Echo(arg0 context.Context, arg1 interface{}) *redis.StringCmd {
	return m.defaultConn.Echo(arg0, arg1)
}

func (m *Manager) Eval(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.Eval(arg0, arg1, arg2, arg3...)
}

func (m *Manager) EvalRO(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.EvalRO(arg0, arg1, arg2, arg3...)
}

func (m *Manager) EvalSha(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.EvalSha(arg0, arg1, arg2, arg3...)
}

func (m *Manager) EvalShaRO(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.EvalShaRO(arg0, arg1, arg2, arg3...)
}

func (m *Manager) Exists(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.Exists(arg0, arg1...)
}

func (m *Manager) Expire(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.Expire(arg0, arg1, arg2)
}

func (m *Manager) ExpireAt(arg0 context.Context, arg1 string, arg2 time.Time) *redis.BoolCmd {
	return m.defaultConn.ExpireAt(arg0, arg1, arg2)
}

func (m *Manager) ExpireGT(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.ExpireGT(arg0, arg1, arg2)
}

func (m *Manager) ExpireLT(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.ExpireLT(arg0, arg1, arg2)
}

func (m *Manager) ExpireNX(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.ExpireNX(arg0, arg1, arg2)
}

func (m *Manager) ExpireTime(arg0 context.Context, arg1 string) *redis.DurationCmd {
	return m.defaultConn.ExpireTime(arg0, arg1)
}

func (m *Manager) ExpireXX(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.ExpireXX(arg0, arg1, arg2)
}

func (m *Manager) FCall(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.FCall(arg0, arg1, arg2, arg3...)
}

func (m *Manager) FCallRO(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.FCallRO(arg0, arg1, arg2, arg3...)
}

func (m *Manager) FCallRo(arg0 context.Context, arg1 string, arg2 []string, arg3 ...interface{}) *redis.Cmd {
	return m.defaultConn.FCallRo(arg0, arg1, arg2, arg3...)
}

func (m *Manager) FTAggregate(arg0 context.Context, arg1 string, arg2 string) *redis.MapStringInterfaceCmd {
	return m.defaultConn.FTAggregate(arg0, arg1, arg2)
}

func (m *Manager) FTAggregateWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.FTAggregateOptions) *redis.AggregateCmd {
	return m.defaultConn.FTAggregateWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTAliasAdd(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.FTAliasAdd(arg0, arg1, arg2)
}

func (m *Manager) FTAliasDel(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.FTAliasDel(arg0, arg1)
}

func (m *Manager) FTAliasUpdate(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.FTAliasUpdate(arg0, arg1, arg2)
}

func (m *Manager) FTAlter(arg0 context.Context, arg1 string, arg2 bool, arg3 []interface{}) *redis.StatusCmd {
	return m.defaultConn.FTAlter(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTConfigGet(arg0 context.Context, arg1 string) *redis.MapMapStringInterfaceCmd {
	return m.defaultConn.FTConfigGet(arg0, arg1)
}

func (m *Manager) FTConfigSet(arg0 context.Context, arg1 string, arg2 interface{}) *redis.StatusCmd {
	return m.defaultConn.FTConfigSet(arg0, arg1, arg2)
}

func (m *Manager) FTCreate(arg0 context.Context, arg1 string, arg2 *redis.FTCreateOptions, arg3 ...*redis.FieldSchema) *redis.StatusCmd {
	return m.defaultConn.FTCreate(arg0, arg1, arg2, arg3...)
}

func (m *Manager) FTCursorDel(arg0 context.Context, arg1 string, arg2 int) *redis.StatusCmd {
	return m.defaultConn.FTCursorDel(arg0, arg1, arg2)
}

func (m *Manager) FTCursorRead(arg0 context.Context, arg1 string, arg2 int, arg3 int) *redis.MapStringInterfaceCmd {
	return m.defaultConn.FTCursorRead(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTDictAdd(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.FTDictAdd(arg0, arg1, arg2...)
}

func (m *Manager) FTDictDel(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.FTDictDel(arg0, arg1, arg2...)
}

func (m *Manager) FTDictDump(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.FTDictDump(arg0, arg1)
}

func (m *Manager) FTDropIndex(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.FTDropIndex(arg0, arg1)
}

func (m *Manager) FTDropIndexWithArgs(arg0 context.Context, arg1 string, arg2 *redis.FTDropIndexOptions) *redis.StatusCmd {
	return m.defaultConn.FTDropIndexWithArgs(arg0, arg1, arg2)
}

func (m *Manager) FTExplain(arg0 context.Context, arg1 string, arg2 string) *redis.StringCmd {
	return m.defaultConn.FTExplain(arg0, arg1, arg2)
}

func (m *Manager) FTExplainCli(arg0 context.Context, arg1 string, arg2 string) error {
	return m.defaultConn.FTExplainCli(arg0, arg1, arg2)
}

func (m *Manager) FTExplainWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.FTExplainOptions) *redis.StringCmd {
	return m.defaultConn.FTExplainWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTHybrid(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 redis.Vector) *redis.FTHybridCmd {
	return m.defaultConn.FTHybrid(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) FTHybridWithArgs(arg0 context.Context, arg1 string, arg2 *redis.FTHybridOptions) *redis.FTHybridCmd {
	return m.defaultConn.FTHybridWithArgs(arg0, arg1, arg2)
}

func (m *Manager) FTInfo(arg0 context.Context, arg1 string) *redis.FTInfoCmd {
	return m.defaultConn.FTInfo(arg0, arg1)
}

func (m *Manager) FTSearch(arg0 context.Context, arg1 string, arg2 string) *redis.FTSearchCmd {
	return m.defaultConn.FTSearch(arg0, arg1, arg2)
}

func (m *Manager) FTSearchWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.FTSearchOptions) *redis.FTSearchCmd {
	return m.defaultConn.FTSearchWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTSpellCheck(arg0 context.Context, arg1 string, arg2 string) *redis.FTSpellCheckCmd {
	return m.defaultConn.FTSpellCheck(arg0, arg1, arg2)
}

func (m *Manager) FTSpellCheckWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.FTSpellCheckOptions) *redis.FTSpellCheckCmd {
	return m.defaultConn.FTSpellCheckWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTSynDump(arg0 context.Context, arg1 string) *redis.FTSynDumpCmd {
	return m.defaultConn.FTSynDump(arg0, arg1)
}

func (m *Manager) FTSynUpdate(arg0 context.Context, arg1 string, arg2 interface{}, arg3 []interface{}) *redis.StatusCmd {
	return m.defaultConn.FTSynUpdate(arg0, arg1, arg2, arg3)
}

func (m *Manager) FTSynUpdateWithArgs(arg0 context.Context, arg1 string, arg2 interface{}, arg3 *redis.FTSynUpdateOptions, arg4 []interface{}) *redis.StatusCmd {
	return m.defaultConn.FTSynUpdateWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) FTTagVals(arg0 context.Context, arg1 string, arg2 string) *redis.StringSliceCmd {
	return m.defaultConn.FTTagVals(arg0, arg1, arg2)
}

func (m *Manager) FT_List(arg0 context.Context) *redis.StringSliceCmd {
	return m.defaultConn.FT_List(arg0)
}

func (m *Manager) FlushAll(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.FlushAll(arg0)
}

func (m *Manager) FlushAllAsync(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.FlushAllAsync(arg0)
}

func (m *Manager) FlushDB(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.FlushDB(arg0)
}

func (m *Manager) FlushDBAsync(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.FlushDBAsync(arg0)
}

func (m *Manager) FunctionDelete(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.FunctionDelete(arg0, arg1)
}

func (m *Manager) FunctionDump(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.FunctionDump(arg0)
}

func (m *Manager) FunctionFlush(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.FunctionFlush(arg0)
}

func (m *Manager) FunctionFlushAsync(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.FunctionFlushAsync(arg0)
}

func (m *Manager) FunctionKill(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.FunctionKill(arg0)
}

func (m *Manager) FunctionList(arg0 context.Context, arg1 redis.FunctionListQuery) *redis.FunctionListCmd {
	return m.defaultConn.FunctionList(arg0, arg1)
}

func (m *Manager) FunctionLoad(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.FunctionLoad(arg0, arg1)
}

func (m *Manager) FunctionLoadReplace(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.FunctionLoadReplace(arg0, arg1)
}

func (m *Manager) FunctionRestore(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.FunctionRestore(arg0, arg1)
}

func (m *Manager) FunctionStats(arg0 context.Context) *redis.FunctionStatsCmd {
	return m.defaultConn.FunctionStats(arg0)
}

func (m *Manager) GeoAdd(arg0 context.Context, arg1 string, arg2 ...*redis.GeoLocation) *redis.IntCmd {
	return m.defaultConn.GeoAdd(arg0, arg1, arg2...)
}

func (m *Manager) GeoDist(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 string) *redis.FloatCmd {
	return m.defaultConn.GeoDist(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) GeoHash(arg0 context.Context, arg1 string, arg2 ...string) *redis.StringSliceCmd {
	return m.defaultConn.GeoHash(arg0, arg1, arg2...)
}

func (m *Manager) GeoPos(arg0 context.Context, arg1 string, arg2 ...string) *redis.GeoPosCmd {
	return m.defaultConn.GeoPos(arg0, arg1, arg2...)
}

func (m *Manager) GeoRadius(arg0 context.Context, arg1 string, arg2 float64, arg3 float64, arg4 *redis.GeoRadiusQuery) *redis.GeoLocationCmd {
	return m.defaultConn.GeoRadius(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) GeoRadiusByMember(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.GeoRadiusQuery) *redis.GeoLocationCmd {
	return m.defaultConn.GeoRadiusByMember(arg0, arg1, arg2, arg3)
}

func (m *Manager) GeoRadiusByMemberStore(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.GeoRadiusQuery) *redis.IntCmd {
	return m.defaultConn.GeoRadiusByMemberStore(arg0, arg1, arg2, arg3)
}

func (m *Manager) GeoRadiusStore(arg0 context.Context, arg1 string, arg2 float64, arg3 float64, arg4 *redis.GeoRadiusQuery) *redis.IntCmd {
	return m.defaultConn.GeoRadiusStore(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) GeoSearch(arg0 context.Context, arg1 string, arg2 *redis.GeoSearchQuery) *redis.StringSliceCmd {
	return m.defaultConn.GeoSearch(arg0, arg1, arg2)
}

func (m *Manager) GeoSearchLocation(arg0 context.Context, arg1 string, arg2 *redis.GeoSearchLocationQuery) *redis.GeoSearchLocationCmd {
	return m.defaultConn.GeoSearchLocation(arg0, arg1, arg2)
}

func (m *Manager) GeoSearchStore(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.GeoSearchStoreQuery) *redis.IntCmd {
	return m.defaultConn.GeoSearchStore(arg0, arg1, arg2, arg3)
}

func (m *Manager) Get(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.Get(arg0, arg1)
}

func (m *Manager) GetBit(arg0 context.Context, arg1 string, arg2 int64) *redis.IntCmd {
	return m.defaultConn.GetBit(arg0, arg1, arg2)
}

func (m *Manager) GetDel(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.GetDel(arg0, arg1)
}

func (m *Manager) GetEx(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.StringCmd {
	return m.defaultConn.GetEx(arg0, arg1, arg2)
}

func (m *Manager) GetMaintNotificationsManager() *maintnotifications.Manager {
	return m.defaultConn.GetMaintNotificationsManager()
}

func (m *Manager) GetPushNotificationHandler(arg0 string) push.NotificationHandler {
	return m.defaultConn.GetPushNotificationHandler(arg0)
}

func (m *Manager) GetRange(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StringCmd {
	return m.defaultConn.GetRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) GetSet(arg0 context.Context, arg1 string, arg2 interface{}) *redis.StringCmd {
	return m.defaultConn.GetSet(arg0, arg1, arg2)
}

func (m *Manager) HDel(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.HDel(arg0, arg1, arg2...)
}

func (m *Manager) HExists(arg0 context.Context, arg1 string, arg2 string) *redis.BoolCmd {
	return m.defaultConn.HExists(arg0, arg1, arg2)
}

func (m *Manager) HExpire(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HExpire(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HExpireAt(arg0 context.Context, arg1 string, arg2 time.Time, arg3 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HExpireAt(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HExpireAtWithArgs(arg0 context.Context, arg1 string, arg2 time.Time, arg3 redis.HExpireArgs, arg4 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HExpireAtWithArgs(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) HExpireTime(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HExpireTime(arg0, arg1, arg2...)
}

func (m *Manager) HExpireWithArgs(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 redis.HExpireArgs, arg4 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HExpireWithArgs(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) HGet(arg0 context.Context, arg1 string, arg2 string) *redis.StringCmd {
	return m.defaultConn.HGet(arg0, arg1, arg2)
}

func (m *Manager) HGetAll(arg0 context.Context, arg1 string) *redis.MapStringStringCmd {
	return m.defaultConn.HGetAll(arg0, arg1)
}

func (m *Manager) HGetDel(arg0 context.Context, arg1 string, arg2 ...string) *redis.StringSliceCmd {
	return m.defaultConn.HGetDel(arg0, arg1, arg2...)
}

func (m *Manager) HGetEX(arg0 context.Context, arg1 string, arg2 ...string) *redis.StringSliceCmd {
	return m.defaultConn.HGetEX(arg0, arg1, arg2...)
}

func (m *Manager) HGetEXWithArgs(arg0 context.Context, arg1 string, arg2 *redis.HGetEXOptions, arg3 ...string) *redis.StringSliceCmd {
	return m.defaultConn.HGetEXWithArgs(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HIncrBy(arg0 context.Context, arg1 string, arg2 string, arg3 int64) *redis.IntCmd {
	return m.defaultConn.HIncrBy(arg0, arg1, arg2, arg3)
}

func (m *Manager) HIncrByFloat(arg0 context.Context, arg1 string, arg2 string, arg3 float64) *redis.FloatCmd {
	return m.defaultConn.HIncrByFloat(arg0, arg1, arg2, arg3)
}

func (m *Manager) HKeys(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.HKeys(arg0, arg1)
}

func (m *Manager) HLen(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.HLen(arg0, arg1)
}

func (m *Manager) HMGet(arg0 context.Context, arg1 string, arg2 ...string) *redis.SliceCmd {
	return m.defaultConn.HMGet(arg0, arg1, arg2...)
}

func (m *Manager) HMSet(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolCmd {
	return m.defaultConn.HMSet(arg0, arg1, arg2...)
}

func (m *Manager) HPExpire(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPExpire(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HPExpireAt(arg0 context.Context, arg1 string, arg2 time.Time, arg3 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPExpireAt(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HPExpireAtWithArgs(arg0 context.Context, arg1 string, arg2 time.Time, arg3 redis.HExpireArgs, arg4 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPExpireAtWithArgs(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) HPExpireTime(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPExpireTime(arg0, arg1, arg2...)
}

func (m *Manager) HPExpireWithArgs(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 redis.HExpireArgs, arg4 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPExpireWithArgs(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) HPTTL(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPTTL(arg0, arg1, arg2...)
}

func (m *Manager) HPersist(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HPersist(arg0, arg1, arg2...)
}

func (m *Manager) HRandField(arg0 context.Context, arg1 string, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.HRandField(arg0, arg1, arg2)
}

func (m *Manager) HRandFieldWithValues(arg0 context.Context, arg1 string, arg2 int) *redis.KeyValueSliceCmd {
	return m.defaultConn.HRandFieldWithValues(arg0, arg1, arg2)
}

func (m *Manager) HScan(arg0 context.Context, arg1 string, arg2 uint64, arg3 string, arg4 int64) *redis.ScanCmd {
	return m.defaultConn.HScan(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) HScanNoValues(arg0 context.Context, arg1 string, arg2 uint64, arg3 string, arg4 int64) *redis.ScanCmd {
	return m.defaultConn.HScanNoValues(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) HSet(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.HSet(arg0, arg1, arg2...)
}

func (m *Manager) HSetEX(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.HSetEX(arg0, arg1, arg2...)
}

func (m *Manager) HSetEXWithArgs(arg0 context.Context, arg1 string, arg2 *redis.HSetEXOptions, arg3 ...string) *redis.IntCmd {
	return m.defaultConn.HSetEXWithArgs(arg0, arg1, arg2, arg3...)
}

func (m *Manager) HSetNX(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}) *redis.BoolCmd {
	return m.defaultConn.HSetNX(arg0, arg1, arg2, arg3)
}

func (m *Manager) HStrLen(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.HStrLen(arg0, arg1, arg2)
}

func (m *Manager) HTTL(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntSliceCmd {
	return m.defaultConn.HTTL(arg0, arg1, arg2...)
}

func (m *Manager) HVals(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.HVals(arg0, arg1)
}

func (m *Manager) Incr(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.Incr(arg0, arg1)
}

func (m *Manager) IncrBy(arg0 context.Context, arg1 string, arg2 int64) *redis.IntCmd {
	return m.defaultConn.IncrBy(arg0, arg1, arg2)
}

func (m *Manager) IncrByFloat(arg0 context.Context, arg1 string, arg2 float64) *redis.FloatCmd {
	return m.defaultConn.IncrByFloat(arg0, arg1, arg2)
}

func (m *Manager) Info(arg0 context.Context, arg1 ...string) *redis.StringCmd {
	return m.defaultConn.Info(arg0, arg1...)
}

func (m *Manager) InfoMap(arg0 context.Context, arg1 ...string) *redis.InfoCmd {
	return m.defaultConn.InfoMap(arg0, arg1...)
}

func (m *Manager) JSONArrAppend(arg0 context.Context, arg1 string, arg2 string, arg3 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrAppend(arg0, arg1, arg2, arg3...)
}

func (m *Manager) JSONArrIndex(arg0 context.Context, arg1 string, arg2 string, arg3 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrIndex(arg0, arg1, arg2, arg3...)
}

func (m *Manager) JSONArrIndexWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.JSONArrIndexArgs, arg4 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrIndexWithArgs(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) JSONArrInsert(arg0 context.Context, arg1 string, arg2 string, arg3 int64, arg4 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrInsert(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) JSONArrLen(arg0 context.Context, arg1 string, arg2 string) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrLen(arg0, arg1, arg2)
}

func (m *Manager) JSONArrPop(arg0 context.Context, arg1 string, arg2 string, arg3 int) *redis.StringSliceCmd {
	return m.defaultConn.JSONArrPop(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONArrTrim(arg0 context.Context, arg1 string, arg2 string) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrTrim(arg0, arg1, arg2)
}

func (m *Manager) JSONArrTrimWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.JSONArrTrimArgs) *redis.IntSliceCmd {
	return m.defaultConn.JSONArrTrimWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONClear(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.JSONClear(arg0, arg1, arg2)
}

func (m *Manager) JSONDebugMemory(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.JSONDebugMemory(arg0, arg1, arg2)
}

func (m *Manager) JSONDel(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.JSONDel(arg0, arg1, arg2)
}

func (m *Manager) JSONForget(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.JSONForget(arg0, arg1, arg2)
}

func (m *Manager) JSONGet(arg0 context.Context, arg1 string, arg2 ...string) *redis.JSONCmd {
	return m.defaultConn.JSONGet(arg0, arg1, arg2...)
}

func (m *Manager) JSONGetWithArgs(arg0 context.Context, arg1 string, arg2 *redis.JSONGetArgs, arg3 ...string) *redis.JSONCmd {
	return m.defaultConn.JSONGetWithArgs(arg0, arg1, arg2, arg3...)
}

func (m *Manager) JSONMGet(arg0 context.Context, arg1 string, arg2 ...string) *redis.JSONSliceCmd {
	return m.defaultConn.JSONMGet(arg0, arg1, arg2...)
}

func (m *Manager) JSONMSet(arg0 context.Context, arg1 ...interface{}) *redis.StatusCmd {
	return m.defaultConn.JSONMSet(arg0, arg1...)
}

func (m *Manager) JSONMSetArgs(arg0 context.Context, arg1 []redis.JSONSetArgs) *redis.StatusCmd {
	return m.defaultConn.JSONMSetArgs(arg0, arg1)
}

func (m *Manager) JSONMerge(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.StatusCmd {
	return m.defaultConn.JSONMerge(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONNumIncrBy(arg0 context.Context, arg1 string, arg2 string, arg3 float64) *redis.JSONCmd {
	return m.defaultConn.JSONNumIncrBy(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONObjKeys(arg0 context.Context, arg1 string, arg2 string) *redis.SliceCmd {
	return m.defaultConn.JSONObjKeys(arg0, arg1, arg2)
}

func (m *Manager) JSONObjLen(arg0 context.Context, arg1 string, arg2 string) *redis.IntPointerSliceCmd {
	return m.defaultConn.JSONObjLen(arg0, arg1, arg2)
}

func (m *Manager) JSONSet(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}) *redis.StatusCmd {
	return m.defaultConn.JSONSet(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONSetMode(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}, arg4 string) *redis.StatusCmd {
	return m.defaultConn.JSONSetMode(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) JSONStrAppend(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntPointerSliceCmd {
	return m.defaultConn.JSONStrAppend(arg0, arg1, arg2, arg3)
}

func (m *Manager) JSONStrLen(arg0 context.Context, arg1 string, arg2 string) *redis.IntPointerSliceCmd {
	return m.defaultConn.JSONStrLen(arg0, arg1, arg2)
}

func (m *Manager) JSONToggle(arg0 context.Context, arg1 string, arg2 string) *redis.IntPointerSliceCmd {
	return m.defaultConn.JSONToggle(arg0, arg1, arg2)
}

func (m *Manager) JSONType(arg0 context.Context, arg1 string, arg2 string) *redis.JSONSliceCmd {
	return m.defaultConn.JSONType(arg0, arg1, arg2)
}

func (m *Manager) Keys(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.Keys(arg0, arg1)
}

func (m *Manager) LCS(arg0 context.Context, arg1 *redis.LCSQuery) *redis.LCSCmd {
	return m.defaultConn.LCS(arg0, arg1)
}

func (m *Manager) LIndex(arg0 context.Context, arg1 string, arg2 int64) *redis.StringCmd {
	return m.defaultConn.LIndex(arg0, arg1, arg2)
}

func (m *Manager) LInsert(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}, arg4 interface{}) *redis.IntCmd {
	return m.defaultConn.LInsert(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) LInsertAfter(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}) *redis.IntCmd {
	return m.defaultConn.LInsertAfter(arg0, arg1, arg2, arg3)
}

func (m *Manager) LInsertBefore(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}) *redis.IntCmd {
	return m.defaultConn.LInsertBefore(arg0, arg1, arg2, arg3)
}

func (m *Manager) LLen(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.LLen(arg0, arg1)
}

func (m *Manager) LMPop(arg0 context.Context, arg1 string, arg2 int64, arg3 ...string) *redis.KeyValuesCmd {
	return m.defaultConn.LMPop(arg0, arg1, arg2, arg3...)
}

func (m *Manager) LMove(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 string) *redis.StringCmd {
	return m.defaultConn.LMove(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) LPop(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.LPop(arg0, arg1)
}

func (m *Manager) LPopCount(arg0 context.Context, arg1 string, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.LPopCount(arg0, arg1, arg2)
}

func (m *Manager) LPos(arg0 context.Context, arg1 string, arg2 string, arg3 redis.LPosArgs) *redis.IntCmd {
	return m.defaultConn.LPos(arg0, arg1, arg2, arg3)
}

func (m *Manager) LPosCount(arg0 context.Context, arg1 string, arg2 string, arg3 int64, arg4 redis.LPosArgs) *redis.IntSliceCmd {
	return m.defaultConn.LPosCount(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) LPush(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.LPush(arg0, arg1, arg2...)
}

func (m *Manager) LPushX(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.LPushX(arg0, arg1, arg2...)
}

func (m *Manager) LRange(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StringSliceCmd {
	return m.defaultConn.LRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) LRem(arg0 context.Context, arg1 string, arg2 int64, arg3 interface{}) *redis.IntCmd {
	return m.defaultConn.LRem(arg0, arg1, arg2, arg3)
}

func (m *Manager) LSet(arg0 context.Context, arg1 string, arg2 int64, arg3 interface{}) *redis.StatusCmd {
	return m.defaultConn.LSet(arg0, arg1, arg2, arg3)
}

func (m *Manager) LTrim(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StatusCmd {
	return m.defaultConn.LTrim(arg0, arg1, arg2, arg3)
}

func (m *Manager) LastSave(arg0 context.Context) *redis.IntCmd {
	return m.defaultConn.LastSave(arg0)
}

func (m *Manager) Latency(arg0 context.Context) *redis.LatencyCmd {
	return m.defaultConn.Latency(arg0)
}

func (m *Manager) LatencyReset(arg0 context.Context, arg1 ...interface{}) *redis.StatusCmd {
	return m.defaultConn.LatencyReset(arg0, arg1...)
}

func (m *Manager) MGet(arg0 context.Context, arg1 ...string) *redis.SliceCmd {
	return m.defaultConn.MGet(arg0, arg1...)
}

func (m *Manager) MSet(arg0 context.Context, arg1 ...interface{}) *redis.StatusCmd {
	return m.defaultConn.MSet(arg0, arg1...)
}

func (m *Manager) MSetEX(arg0 context.Context, arg1 redis.MSetEXArgs, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.MSetEX(arg0, arg1, arg2...)
}

func (m *Manager) MSetNX(arg0 context.Context, arg1 ...interface{}) *redis.BoolCmd {
	return m.defaultConn.MSetNX(arg0, arg1...)
}

func (m *Manager) MemoryUsage(arg0 context.Context, arg1 string, arg2 ...int) *redis.IntCmd {
	return m.defaultConn.MemoryUsage(arg0, arg1, arg2...)
}

func (m *Manager) Migrate(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 int, arg5 time.Duration) *redis.StatusCmd {
	return m.defaultConn.Migrate(arg0, arg1, arg2, arg3, arg4, arg5)
}

func (m *Manager) ModuleLoadex(arg0 context.Context, arg1 *redis.ModuleLoadexConfig) *redis.StringCmd {
	return m.defaultConn.ModuleLoadex(arg0, arg1)
}

func (m *Manager) Monitor(arg0 context.Context, arg1 chan string) *redis.MonitorCmd {
	return m.defaultConn.Monitor(arg0, arg1)
}

func (m *Manager) Move(arg0 context.Context, arg1 string, arg2 int) *redis.BoolCmd {
	return m.defaultConn.Move(arg0, arg1, arg2)
}

func (m *Manager) NewAggregateBuilder(arg0 context.Context, arg1 string, arg2 string) *redis.AggregateBuilder {
	return m.defaultConn.NewAggregateBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewAliasBuilder(arg0 context.Context, arg1 string) *redis.AliasBuilder {
	return m.defaultConn.NewAliasBuilder(arg0, arg1)
}

func (m *Manager) NewCreateIndexBuilder(arg0 context.Context, arg1 string) *redis.CreateIndexBuilder {
	return m.defaultConn.NewCreateIndexBuilder(arg0, arg1)
}

func (m *Manager) NewCursorBuilder(arg0 context.Context, arg1 string, arg2 int64) *redis.CursorBuilder {
	return m.defaultConn.NewCursorBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewDictBuilder(arg0 context.Context, arg1 string) *redis.DictBuilder {
	return m.defaultConn.NewDictBuilder(arg0, arg1)
}

func (m *Manager) NewDropIndexBuilder(arg0 context.Context, arg1 string) *redis.DropIndexBuilder {
	return m.defaultConn.NewDropIndexBuilder(arg0, arg1)
}

func (m *Manager) NewExplainBuilder(arg0 context.Context, arg1 string, arg2 string) *redis.ExplainBuilder {
	return m.defaultConn.NewExplainBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewSearchBuilder(arg0 context.Context, arg1 string, arg2 string) *redis.SearchBuilder {
	return m.defaultConn.NewSearchBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewSearchInfoBuilder(arg0 context.Context, arg1 string) *redis.FTInfoBuilder {
	return m.defaultConn.NewSearchInfoBuilder(arg0, arg1)
}

func (m *Manager) NewSpellCheckBuilder(arg0 context.Context, arg1 string, arg2 string) *redis.SpellCheckBuilder {
	return m.defaultConn.NewSpellCheckBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewSynUpdateBuilder(arg0 context.Context, arg1 string, arg2 interface{}) *redis.SynUpdateBuilder {
	return m.defaultConn.NewSynUpdateBuilder(arg0, arg1, arg2)
}

func (m *Manager) NewTagValsBuilder(arg0 context.Context, arg1 string, arg2 string) *redis.TagValsBuilder {
	return m.defaultConn.NewTagValsBuilder(arg0, arg1, arg2)
}

func (m *Manager) ObjectEncoding(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.ObjectEncoding(arg0, arg1)
}

func (m *Manager) ObjectFreq(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ObjectFreq(arg0, arg1)
}

func (m *Manager) ObjectIdleTime(arg0 context.Context, arg1 string) *redis.DurationCmd {
	return m.defaultConn.ObjectIdleTime(arg0, arg1)
}

func (m *Manager) ObjectRefCount(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ObjectRefCount(arg0, arg1)
}

func (m *Manager) Options() *redis.Options {
	return m.defaultConn.Options()
}

func (m *Manager) PExpire(arg0 context.Context, arg1 string, arg2 time.Duration) *redis.BoolCmd {
	return m.defaultConn.PExpire(arg0, arg1, arg2)
}

func (m *Manager) PExpireAt(arg0 context.Context, arg1 string, arg2 time.Time) *redis.BoolCmd {
	return m.defaultConn.PExpireAt(arg0, arg1, arg2)
}

func (m *Manager) PExpireTime(arg0 context.Context, arg1 string) *redis.DurationCmd {
	return m.defaultConn.PExpireTime(arg0, arg1)
}

func (m *Manager) PFAdd(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.PFAdd(arg0, arg1, arg2...)
}

func (m *Manager) PFCount(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.PFCount(arg0, arg1...)
}

func (m *Manager) PFMerge(arg0 context.Context, arg1 string, arg2 ...string) *redis.StatusCmd {
	return m.defaultConn.PFMerge(arg0, arg1, arg2...)
}

func (m *Manager) PSubscribe(arg0 context.Context, arg1 ...string) *redis.PubSub {
	return m.defaultConn.PSubscribe(arg0, arg1...)
}

func (m *Manager) PTTL(arg0 context.Context, arg1 string) *redis.DurationCmd {
	return m.defaultConn.PTTL(arg0, arg1)
}

func (m *Manager) Persist(arg0 context.Context, arg1 string) *redis.BoolCmd {
	return m.defaultConn.Persist(arg0, arg1)
}

func (m *Manager) Ping(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.Ping(arg0)
}

func (m *Manager) Pipeline() redis.Pipeliner {
	return m.defaultConn.Pipeline()
}

func (m *Manager) Pipelined(arg0 context.Context, arg1 func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	return m.defaultConn.Pipelined(arg0, arg1)
}

func (m *Manager) PoolStats() *redis.PoolStats {
	return m.defaultConn.PoolStats()
}

func (m *Manager) Process(arg0 context.Context, arg1 redis.Cmder) error {
	return m.defaultConn.Process(arg0, arg1)
}

func (m *Manager) PubSubChannels(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.PubSubChannels(arg0, arg1)
}

func (m *Manager) PubSubNumPat(arg0 context.Context) *redis.IntCmd {
	return m.defaultConn.PubSubNumPat(arg0)
}

func (m *Manager) PubSubNumSub(arg0 context.Context, arg1 ...string) *redis.MapStringIntCmd {
	return m.defaultConn.PubSubNumSub(arg0, arg1...)
}

func (m *Manager) PubSubShardChannels(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.PubSubShardChannels(arg0, arg1)
}

func (m *Manager) PubSubShardNumSub(arg0 context.Context, arg1 ...string) *redis.MapStringIntCmd {
	return m.defaultConn.PubSubShardNumSub(arg0, arg1...)
}

func (m *Manager) Publish(arg0 context.Context, arg1 string, arg2 interface{}) *redis.IntCmd {
	return m.defaultConn.Publish(arg0, arg1, arg2)
}

func (m *Manager) Quit(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.Quit(arg0)
}

func (m *Manager) RPop(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.RPop(arg0, arg1)
}

func (m *Manager) RPopCount(arg0 context.Context, arg1 string, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.RPopCount(arg0, arg1, arg2)
}

func (m *Manager) RPopLPush(arg0 context.Context, arg1 string, arg2 string) *redis.StringCmd {
	return m.defaultConn.RPopLPush(arg0, arg1, arg2)
}

func (m *Manager) RPush(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.RPush(arg0, arg1, arg2...)
}

func (m *Manager) RPushX(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.RPushX(arg0, arg1, arg2...)
}

func (m *Manager) RandomKey(arg0 context.Context) *redis.StringCmd {
	return m.defaultConn.RandomKey(arg0)
}

func (m *Manager) ReadOnly(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ReadOnly(arg0)
}

func (m *Manager) ReadWrite(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ReadWrite(arg0)
}

func (m *Manager) RegisterPushNotificationHandler(arg0 string, arg1 push.NotificationHandler, arg2 bool) error {
	return m.defaultConn.RegisterPushNotificationHandler(arg0, arg1, arg2)
}

func (m *Manager) Rename(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.Rename(arg0, arg1, arg2)
}

func (m *Manager) RenameNX(arg0 context.Context, arg1 string, arg2 string) *redis.BoolCmd {
	return m.defaultConn.RenameNX(arg0, arg1, arg2)
}

func (m *Manager) Restore(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 string) *redis.StatusCmd {
	return m.defaultConn.Restore(arg0, arg1, arg2, arg3)
}

func (m *Manager) RestoreReplace(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 string) *redis.StatusCmd {
	return m.defaultConn.RestoreReplace(arg0, arg1, arg2, arg3)
}

func (m *Manager) SAdd(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.SAdd(arg0, arg1, arg2...)
}

func (m *Manager) SCard(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.SCard(arg0, arg1)
}

func (m *Manager) SDiff(arg0 context.Context, arg1 ...string) *redis.StringSliceCmd {
	return m.defaultConn.SDiff(arg0, arg1...)
}

func (m *Manager) SDiffStore(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.SDiffStore(arg0, arg1, arg2...)
}

func (m *Manager) SInter(arg0 context.Context, arg1 ...string) *redis.StringSliceCmd {
	return m.defaultConn.SInter(arg0, arg1...)
}

func (m *Manager) SInterCard(arg0 context.Context, arg1 int64, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.SInterCard(arg0, arg1, arg2...)
}

func (m *Manager) SInterStore(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.SInterStore(arg0, arg1, arg2...)
}

func (m *Manager) SIsMember(arg0 context.Context, arg1 string, arg2 interface{}) *redis.BoolCmd {
	return m.defaultConn.SIsMember(arg0, arg1, arg2)
}

func (m *Manager) SMIsMember(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.SMIsMember(arg0, arg1, arg2...)
}

func (m *Manager) SMembers(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.SMembers(arg0, arg1)
}

func (m *Manager) SMembersMap(arg0 context.Context, arg1 string) *redis.StringStructMapCmd {
	return m.defaultConn.SMembersMap(arg0, arg1)
}

func (m *Manager) SMove(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}) *redis.BoolCmd {
	return m.defaultConn.SMove(arg0, arg1, arg2, arg3)
}

func (m *Manager) SPop(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.SPop(arg0, arg1)
}

func (m *Manager) SPopN(arg0 context.Context, arg1 string, arg2 int64) *redis.StringSliceCmd {
	return m.defaultConn.SPopN(arg0, arg1, arg2)
}

func (m *Manager) SPublish(arg0 context.Context, arg1 string, arg2 interface{}) *redis.IntCmd {
	return m.defaultConn.SPublish(arg0, arg1, arg2)
}

func (m *Manager) SRandMember(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.SRandMember(arg0, arg1)
}

func (m *Manager) SRandMemberN(arg0 context.Context, arg1 string, arg2 int64) *redis.StringSliceCmd {
	return m.defaultConn.SRandMemberN(arg0, arg1, arg2)
}

func (m *Manager) SRem(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.SRem(arg0, arg1, arg2...)
}

func (m *Manager) SScan(arg0 context.Context, arg1 string, arg2 uint64, arg3 string, arg4 int64) *redis.ScanCmd {
	return m.defaultConn.SScan(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SSubscribe(arg0 context.Context, arg1 ...string) *redis.PubSub {
	return m.defaultConn.SSubscribe(arg0, arg1...)
}

func (m *Manager) SUnion(arg0 context.Context, arg1 ...string) *redis.StringSliceCmd {
	return m.defaultConn.SUnion(arg0, arg1...)
}

func (m *Manager) SUnionStore(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.SUnionStore(arg0, arg1, arg2...)
}

func (m *Manager) Save(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.Save(arg0)
}

func (m *Manager) Scan(arg0 context.Context, arg1 uint64, arg2 string, arg3 int64) *redis.ScanCmd {
	return m.defaultConn.Scan(arg0, arg1, arg2, arg3)
}

func (m *Manager) ScanType(arg0 context.Context, arg1 uint64, arg2 string, arg3 int64, arg4 string) *redis.ScanCmd {
	return m.defaultConn.ScanType(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) ScriptExists(arg0 context.Context, arg1 ...string) *redis.BoolSliceCmd {
	return m.defaultConn.ScriptExists(arg0, arg1...)
}

func (m *Manager) ScriptFlush(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ScriptFlush(arg0)
}

func (m *Manager) ScriptKill(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ScriptKill(arg0)
}

func (m *Manager) ScriptLoad(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.ScriptLoad(arg0, arg1)
}

func (m *Manager) Set(arg0 context.Context, arg1 string, arg2 interface{}, arg3 time.Duration) *redis.StatusCmd {
	return m.defaultConn.Set(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetArgs(arg0 context.Context, arg1 string, arg2 interface{}, arg3 redis.SetArgs) *redis.StatusCmd {
	return m.defaultConn.SetArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetBit(arg0 context.Context, arg1 string, arg2 int64, arg3 int) *redis.IntCmd {
	return m.defaultConn.SetBit(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetEx(arg0 context.Context, arg1 string, arg2 interface{}, arg3 time.Duration) *redis.StatusCmd {
	return m.defaultConn.SetEx(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetIFDEQ(arg0 context.Context, arg1 string, arg2 interface{}, arg3 uint64, arg4 time.Duration) *redis.StatusCmd {
	return m.defaultConn.SetIFDEQ(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFDEQGet(arg0 context.Context, arg1 string, arg2 interface{}, arg3 uint64, arg4 time.Duration) *redis.StringCmd {
	return m.defaultConn.SetIFDEQGet(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFDNE(arg0 context.Context, arg1 string, arg2 interface{}, arg3 uint64, arg4 time.Duration) *redis.StatusCmd {
	return m.defaultConn.SetIFDNE(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFDNEGet(arg0 context.Context, arg1 string, arg2 interface{}, arg3 uint64, arg4 time.Duration) *redis.StringCmd {
	return m.defaultConn.SetIFDNEGet(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFEQ(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}, arg4 time.Duration) *redis.StatusCmd {
	return m.defaultConn.SetIFEQ(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFEQGet(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}, arg4 time.Duration) *redis.StringCmd {
	return m.defaultConn.SetIFEQGet(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFNE(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}, arg4 time.Duration) *redis.StatusCmd {
	return m.defaultConn.SetIFNE(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetIFNEGet(arg0 context.Context, arg1 string, arg2 interface{}, arg3 interface{}, arg4 time.Duration) *redis.StringCmd {
	return m.defaultConn.SetIFNEGet(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) SetNX(arg0 context.Context, arg1 string, arg2 interface{}, arg3 time.Duration) *redis.BoolCmd {
	return m.defaultConn.SetNX(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetRange(arg0 context.Context, arg1 string, arg2 int64, arg3 string) *redis.IntCmd {
	return m.defaultConn.SetRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) SetXX(arg0 context.Context, arg1 string, arg2 interface{}, arg3 time.Duration) *redis.BoolCmd {
	return m.defaultConn.SetXX(arg0, arg1, arg2, arg3)
}

func (m *Manager) Shutdown(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.Shutdown(arg0)
}

func (m *Manager) ShutdownNoSave(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ShutdownNoSave(arg0)
}

func (m *Manager) ShutdownSave(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.ShutdownSave(arg0)
}

func (m *Manager) SlaveOf(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.SlaveOf(arg0, arg1, arg2)
}

func (m *Manager) SlowLogGet(arg0 context.Context, arg1 int64) *redis.SlowLogCmd {
	return m.defaultConn.SlowLogGet(arg0, arg1)
}

func (m *Manager) SlowLogLen(arg0 context.Context) *redis.IntCmd {
	return m.defaultConn.SlowLogLen(arg0)
}

func (m *Manager) SlowLogReset(arg0 context.Context) *redis.StatusCmd {
	return m.defaultConn.SlowLogReset(arg0)
}

func (m *Manager) Sort(arg0 context.Context, arg1 string, arg2 *redis.Sort) *redis.StringSliceCmd {
	return m.defaultConn.Sort(arg0, arg1, arg2)
}

func (m *Manager) SortInterfaces(arg0 context.Context, arg1 string, arg2 *redis.Sort) *redis.SliceCmd {
	return m.defaultConn.SortInterfaces(arg0, arg1, arg2)
}

func (m *Manager) SortRO(arg0 context.Context, arg1 string, arg2 *redis.Sort) *redis.StringSliceCmd {
	return m.defaultConn.SortRO(arg0, arg1, arg2)
}

func (m *Manager) SortStore(arg0 context.Context, arg1 string, arg2 string, arg3 *redis.Sort) *redis.IntCmd {
	return m.defaultConn.SortStore(arg0, arg1, arg2, arg3)
}

func (m *Manager) StrLen(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.StrLen(arg0, arg1)
}

func (m *Manager) String() string {
	return m.defaultConn.String()
}

func (m *Manager) Subscribe(arg0 context.Context, arg1 ...string) *redis.PubSub {
	return m.defaultConn.Subscribe(arg0, arg1...)
}

func (m *Manager) Sync(arg0 context.Context) {
	m.defaultConn.Sync(arg0)
}

func (m *Manager) TDigestAdd(arg0 context.Context, arg1 string, arg2 ...float64) *redis.StatusCmd {
	return m.defaultConn.TDigestAdd(arg0, arg1, arg2...)
}

func (m *Manager) TDigestByRank(arg0 context.Context, arg1 string, arg2 ...uint64) *redis.FloatSliceCmd {
	return m.defaultConn.TDigestByRank(arg0, arg1, arg2...)
}

func (m *Manager) TDigestByRevRank(arg0 context.Context, arg1 string, arg2 ...uint64) *redis.FloatSliceCmd {
	return m.defaultConn.TDigestByRevRank(arg0, arg1, arg2...)
}

func (m *Manager) TDigestCDF(arg0 context.Context, arg1 string, arg2 ...float64) *redis.FloatSliceCmd {
	return m.defaultConn.TDigestCDF(arg0, arg1, arg2...)
}

func (m *Manager) TDigestCreate(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.TDigestCreate(arg0, arg1)
}

func (m *Manager) TDigestCreateWithCompression(arg0 context.Context, arg1 string, arg2 int64) *redis.StatusCmd {
	return m.defaultConn.TDigestCreateWithCompression(arg0, arg1, arg2)
}

func (m *Manager) TDigestInfo(arg0 context.Context, arg1 string) *redis.TDigestInfoCmd {
	return m.defaultConn.TDigestInfo(arg0, arg1)
}

func (m *Manager) TDigestMax(arg0 context.Context, arg1 string) *redis.FloatCmd {
	return m.defaultConn.TDigestMax(arg0, arg1)
}

func (m *Manager) TDigestMerge(arg0 context.Context, arg1 string, arg2 *redis.TDigestMergeOptions, arg3 ...string) *redis.StatusCmd {
	return m.defaultConn.TDigestMerge(arg0, arg1, arg2, arg3...)
}

func (m *Manager) TDigestMin(arg0 context.Context, arg1 string) *redis.FloatCmd {
	return m.defaultConn.TDigestMin(arg0, arg1)
}

func (m *Manager) TDigestQuantile(arg0 context.Context, arg1 string, arg2 ...float64) *redis.FloatSliceCmd {
	return m.defaultConn.TDigestQuantile(arg0, arg1, arg2...)
}

func (m *Manager) TDigestRank(arg0 context.Context, arg1 string, arg2 ...float64) *redis.IntSliceCmd {
	return m.defaultConn.TDigestRank(arg0, arg1, arg2...)
}

func (m *Manager) TDigestReset(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.TDigestReset(arg0, arg1)
}

func (m *Manager) TDigestRevRank(arg0 context.Context, arg1 string, arg2 ...float64) *redis.IntSliceCmd {
	return m.defaultConn.TDigestRevRank(arg0, arg1, arg2...)
}

func (m *Manager) TDigestTrimmedMean(arg0 context.Context, arg1 string, arg2 float64, arg3 float64) *redis.FloatCmd {
	return m.defaultConn.TDigestTrimmedMean(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSAdd(arg0 context.Context, arg1 string, arg2 interface{}, arg3 float64) *redis.IntCmd {
	return m.defaultConn.TSAdd(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSAddWithArgs(arg0 context.Context, arg1 string, arg2 interface{}, arg3 float64, arg4 *redis.TSOptions) *redis.IntCmd {
	return m.defaultConn.TSAddWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TSAlter(arg0 context.Context, arg1 string, arg2 *redis.TSAlterOptions) *redis.StatusCmd {
	return m.defaultConn.TSAlter(arg0, arg1, arg2)
}

func (m *Manager) TSCreate(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.TSCreate(arg0, arg1)
}

func (m *Manager) TSCreateRule(arg0 context.Context, arg1 string, arg2 string, arg3 redis.Aggregator, arg4 int) *redis.StatusCmd {
	return m.defaultConn.TSCreateRule(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TSCreateRuleWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 redis.Aggregator, arg4 int, arg5 *redis.TSCreateRuleOptions) *redis.StatusCmd {
	return m.defaultConn.TSCreateRuleWithArgs(arg0, arg1, arg2, arg3, arg4, arg5)
}

func (m *Manager) TSCreateWithArgs(arg0 context.Context, arg1 string, arg2 *redis.TSOptions) *redis.StatusCmd {
	return m.defaultConn.TSCreateWithArgs(arg0, arg1, arg2)
}

func (m *Manager) TSDecrBy(arg0 context.Context, arg1 string, arg2 float64) *redis.IntCmd {
	return m.defaultConn.TSDecrBy(arg0, arg1, arg2)
}

func (m *Manager) TSDecrByWithArgs(arg0 context.Context, arg1 string, arg2 float64, arg3 *redis.TSIncrDecrOptions) *redis.IntCmd {
	return m.defaultConn.TSDecrByWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSDel(arg0 context.Context, arg1 string, arg2 int, arg3 int) *redis.IntCmd {
	return m.defaultConn.TSDel(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSDeleteRule(arg0 context.Context, arg1 string, arg2 string) *redis.StatusCmd {
	return m.defaultConn.TSDeleteRule(arg0, arg1, arg2)
}

func (m *Manager) TSGet(arg0 context.Context, arg1 string) *redis.TSTimestampValueCmd {
	return m.defaultConn.TSGet(arg0, arg1)
}

func (m *Manager) TSGetWithArgs(arg0 context.Context, arg1 string, arg2 *redis.TSGetOptions) *redis.TSTimestampValueCmd {
	return m.defaultConn.TSGetWithArgs(arg0, arg1, arg2)
}

func (m *Manager) TSIncrBy(arg0 context.Context, arg1 string, arg2 float64) *redis.IntCmd {
	return m.defaultConn.TSIncrBy(arg0, arg1, arg2)
}

func (m *Manager) TSIncrByWithArgs(arg0 context.Context, arg1 string, arg2 float64, arg3 *redis.TSIncrDecrOptions) *redis.IntCmd {
	return m.defaultConn.TSIncrByWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSInfo(arg0 context.Context, arg1 string) *redis.MapStringInterfaceCmd {
	return m.defaultConn.TSInfo(arg0, arg1)
}

func (m *Manager) TSInfoWithArgs(arg0 context.Context, arg1 string, arg2 *redis.TSInfoOptions) *redis.MapStringInterfaceCmd {
	return m.defaultConn.TSInfoWithArgs(arg0, arg1, arg2)
}

func (m *Manager) TSMAdd(arg0 context.Context, arg1 [][]interface{}) *redis.IntSliceCmd {
	return m.defaultConn.TSMAdd(arg0, arg1)
}

func (m *Manager) TSMGet(arg0 context.Context, arg1 []string) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMGet(arg0, arg1)
}

func (m *Manager) TSMGetWithArgs(arg0 context.Context, arg1 []string, arg2 *redis.TSMGetOptions) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMGetWithArgs(arg0, arg1, arg2)
}

func (m *Manager) TSMRange(arg0 context.Context, arg1 int, arg2 int, arg3 []string) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSMRangeWithArgs(arg0 context.Context, arg1 int, arg2 int, arg3 []string, arg4 *redis.TSMRangeOptions) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMRangeWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TSMRevRange(arg0 context.Context, arg1 int, arg2 int, arg3 []string) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMRevRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSMRevRangeWithArgs(arg0 context.Context, arg1 int, arg2 int, arg3 []string, arg4 *redis.TSMRevRangeOptions) *redis.MapStringSliceInterfaceCmd {
	return m.defaultConn.TSMRevRangeWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TSQueryIndex(arg0 context.Context, arg1 []string) *redis.StringSliceCmd {
	return m.defaultConn.TSQueryIndex(arg0, arg1)
}

func (m *Manager) TSRange(arg0 context.Context, arg1 string, arg2 int, arg3 int) *redis.TSTimestampValueSliceCmd {
	return m.defaultConn.TSRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSRangeWithArgs(arg0 context.Context, arg1 string, arg2 int, arg3 int, arg4 *redis.TSRangeOptions) *redis.TSTimestampValueSliceCmd {
	return m.defaultConn.TSRangeWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TSRevRange(arg0 context.Context, arg1 string, arg2 int, arg3 int) *redis.TSTimestampValueSliceCmd {
	return m.defaultConn.TSRevRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) TSRevRangeWithArgs(arg0 context.Context, arg1 string, arg2 int, arg3 int, arg4 *redis.TSRevRangeOptions) *redis.TSTimestampValueSliceCmd {
	return m.defaultConn.TSRevRangeWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) TTL(arg0 context.Context, arg1 string) *redis.DurationCmd {
	return m.defaultConn.TTL(arg0, arg1)
}

func (m *Manager) Time(arg0 context.Context) *redis.TimeCmd {
	return m.defaultConn.Time(arg0)
}

func (m *Manager) TopKAdd(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.StringSliceCmd {
	return m.defaultConn.TopKAdd(arg0, arg1, arg2...)
}

func (m *Manager) TopKCount(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntSliceCmd {
	return m.defaultConn.TopKCount(arg0, arg1, arg2...)
}

func (m *Manager) TopKIncrBy(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.StringSliceCmd {
	return m.defaultConn.TopKIncrBy(arg0, arg1, arg2...)
}

func (m *Manager) TopKInfo(arg0 context.Context, arg1 string) *redis.TopKInfoCmd {
	return m.defaultConn.TopKInfo(arg0, arg1)
}

func (m *Manager) TopKList(arg0 context.Context, arg1 string) *redis.StringSliceCmd {
	return m.defaultConn.TopKList(arg0, arg1)
}

func (m *Manager) TopKListWithCount(arg0 context.Context, arg1 string) *redis.MapStringIntCmd {
	return m.defaultConn.TopKListWithCount(arg0, arg1)
}

func (m *Manager) TopKQuery(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.BoolSliceCmd {
	return m.defaultConn.TopKQuery(arg0, arg1, arg2...)
}

func (m *Manager) TopKReserve(arg0 context.Context, arg1 string, arg2 int64) *redis.StatusCmd {
	return m.defaultConn.TopKReserve(arg0, arg1, arg2)
}

func (m *Manager) TopKReserveWithOptions(arg0 context.Context, arg1 string, arg2 int64, arg3 int64, arg4 int64, arg5 float64) *redis.StatusCmd {
	return m.defaultConn.TopKReserveWithOptions(arg0, arg1, arg2, arg3, arg4, arg5)
}

func (m *Manager) Touch(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.Touch(arg0, arg1...)
}

func (m *Manager) TxPipeline() redis.Pipeliner {
	return m.defaultConn.TxPipeline()
}

func (m *Manager) TxPipelined(arg0 context.Context, arg1 func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	return m.defaultConn.TxPipelined(arg0, arg1)
}

func (m *Manager) Type(arg0 context.Context, arg1 string) *redis.StatusCmd {
	return m.defaultConn.Type(arg0, arg1)
}

func (m *Manager) Unlink(arg0 context.Context, arg1 ...string) *redis.IntCmd {
	return m.defaultConn.Unlink(arg0, arg1...)
}

func (m *Manager) VAdd(arg0 context.Context, arg1 string, arg2 string, arg3 redis.Vector) *redis.BoolCmd {
	return m.defaultConn.VAdd(arg0, arg1, arg2, arg3)
}

func (m *Manager) VAddWithArgs(arg0 context.Context, arg1 string, arg2 string, arg3 redis.Vector, arg4 *redis.VAddArgs) *redis.BoolCmd {
	return m.defaultConn.VAddWithArgs(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) VCard(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.VCard(arg0, arg1)
}

func (m *Manager) VClearAttributes(arg0 context.Context, arg1 string, arg2 string) *redis.BoolCmd {
	return m.defaultConn.VClearAttributes(arg0, arg1, arg2)
}

func (m *Manager) VDim(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.VDim(arg0, arg1)
}

func (m *Manager) VEmb(arg0 context.Context, arg1 string, arg2 string, arg3 bool) *redis.SliceCmd {
	return m.defaultConn.VEmb(arg0, arg1, arg2, arg3)
}

func (m *Manager) VGetAttr(arg0 context.Context, arg1 string, arg2 string) *redis.StringCmd {
	return m.defaultConn.VGetAttr(arg0, arg1, arg2)
}

func (m *Manager) VInfo(arg0 context.Context, arg1 string) *redis.MapStringInterfaceCmd {
	return m.defaultConn.VInfo(arg0, arg1)
}

func (m *Manager) VLinks(arg0 context.Context, arg1 string, arg2 string) *redis.StringSliceCmd {
	return m.defaultConn.VLinks(arg0, arg1, arg2)
}

func (m *Manager) VLinksWithScores(arg0 context.Context, arg1 string, arg2 string) *redis.VectorScoreSliceCmd {
	return m.defaultConn.VLinksWithScores(arg0, arg1, arg2)
}

func (m *Manager) VRandMember(arg0 context.Context, arg1 string) *redis.StringCmd {
	return m.defaultConn.VRandMember(arg0, arg1)
}

func (m *Manager) VRandMemberCount(arg0 context.Context, arg1 string, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.VRandMemberCount(arg0, arg1, arg2)
}

func (m *Manager) VRange(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 int64) *redis.StringSliceCmd {
	return m.defaultConn.VRange(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) VRem(arg0 context.Context, arg1 string, arg2 string) *redis.BoolCmd {
	return m.defaultConn.VRem(arg0, arg1, arg2)
}

func (m *Manager) VSetAttr(arg0 context.Context, arg1 string, arg2 string, arg3 interface{}) *redis.BoolCmd {
	return m.defaultConn.VSetAttr(arg0, arg1, arg2, arg3)
}

func (m *Manager) VSim(arg0 context.Context, arg1 string, arg2 redis.Vector) *redis.StringSliceCmd {
	return m.defaultConn.VSim(arg0, arg1, arg2)
}

func (m *Manager) VSimWithArgs(arg0 context.Context, arg1 string, arg2 redis.Vector, arg3 *redis.VSimArgs) *redis.StringSliceCmd {
	return m.defaultConn.VSimWithArgs(arg0, arg1, arg2, arg3)
}

func (m *Manager) VSimWithArgsWithScores(arg0 context.Context, arg1 string, arg2 redis.Vector, arg3 *redis.VSimArgs) *redis.VectorScoreSliceCmd {
	return m.defaultConn.VSimWithArgsWithScores(arg0, arg1, arg2, arg3)
}

func (m *Manager) VSimWithScores(arg0 context.Context, arg1 string, arg2 redis.Vector) *redis.VectorScoreSliceCmd {
	return m.defaultConn.VSimWithScores(arg0, arg1, arg2)
}

func (m *Manager) Wait(arg0 context.Context, arg1 int, arg2 time.Duration) *redis.IntCmd {
	return m.defaultConn.Wait(arg0, arg1, arg2)
}

func (m *Manager) WaitAOF(arg0 context.Context, arg1 int, arg2 int, arg3 time.Duration) *redis.IntCmd {
	return m.defaultConn.WaitAOF(arg0, arg1, arg2, arg3)
}

func (m *Manager) Watch(arg0 context.Context, arg1 func(*redis.Tx) error, arg2 ...string) error {
	return m.defaultConn.Watch(arg0, arg1, arg2...)
}

func (m *Manager) WithTimeout(arg0 time.Duration) *redis.Client {
	return m.defaultConn.WithTimeout(arg0)
}

func (m *Manager) XAck(arg0 context.Context, arg1 string, arg2 string, arg3 ...string) *redis.IntCmd {
	return m.defaultConn.XAck(arg0, arg1, arg2, arg3...)
}

func (m *Manager) XAckDel(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 ...string) *redis.SliceCmd {
	return m.defaultConn.XAckDel(arg0, arg1, arg2, arg3, arg4...)
}

func (m *Manager) XAdd(arg0 context.Context, arg1 *redis.XAddArgs) *redis.StringCmd {
	return m.defaultConn.XAdd(arg0, arg1)
}

func (m *Manager) XAutoClaim(arg0 context.Context, arg1 *redis.XAutoClaimArgs) *redis.XAutoClaimCmd {
	return m.defaultConn.XAutoClaim(arg0, arg1)
}

func (m *Manager) XAutoClaimJustID(arg0 context.Context, arg1 *redis.XAutoClaimArgs) *redis.XAutoClaimJustIDCmd {
	return m.defaultConn.XAutoClaimJustID(arg0, arg1)
}

func (m *Manager) XClaim(arg0 context.Context, arg1 *redis.XClaimArgs) *redis.XMessageSliceCmd {
	return m.defaultConn.XClaim(arg0, arg1)
}

func (m *Manager) XClaimJustID(arg0 context.Context, arg1 *redis.XClaimArgs) *redis.StringSliceCmd {
	return m.defaultConn.XClaimJustID(arg0, arg1)
}

func (m *Manager) XDel(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.XDel(arg0, arg1, arg2...)
}

func (m *Manager) XDelEx(arg0 context.Context, arg1 string, arg2 string, arg3 ...string) *redis.SliceCmd {
	return m.defaultConn.XDelEx(arg0, arg1, arg2, arg3...)
}

func (m *Manager) XGroupCreate(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.StatusCmd {
	return m.defaultConn.XGroupCreate(arg0, arg1, arg2, arg3)
}

func (m *Manager) XGroupCreateConsumer(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.XGroupCreateConsumer(arg0, arg1, arg2, arg3)
}

func (m *Manager) XGroupCreateMkStream(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.StatusCmd {
	return m.defaultConn.XGroupCreateMkStream(arg0, arg1, arg2, arg3)
}

func (m *Manager) XGroupDelConsumer(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.XGroupDelConsumer(arg0, arg1, arg2, arg3)
}

func (m *Manager) XGroupDestroy(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.XGroupDestroy(arg0, arg1, arg2)
}

func (m *Manager) XGroupSetID(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.StatusCmd {
	return m.defaultConn.XGroupSetID(arg0, arg1, arg2, arg3)
}

func (m *Manager) XInfoConsumers(arg0 context.Context, arg1 string, arg2 string) *redis.XInfoConsumersCmd {
	return m.defaultConn.XInfoConsumers(arg0, arg1, arg2)
}

func (m *Manager) XInfoGroups(arg0 context.Context, arg1 string) *redis.XInfoGroupsCmd {
	return m.defaultConn.XInfoGroups(arg0, arg1)
}

func (m *Manager) XInfoStream(arg0 context.Context, arg1 string) *redis.XInfoStreamCmd {
	return m.defaultConn.XInfoStream(arg0, arg1)
}

func (m *Manager) XInfoStreamFull(arg0 context.Context, arg1 string, arg2 int) *redis.XInfoStreamFullCmd {
	return m.defaultConn.XInfoStreamFull(arg0, arg1, arg2)
}

func (m *Manager) XLen(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.XLen(arg0, arg1)
}

func (m *Manager) XPending(arg0 context.Context, arg1 string, arg2 string) *redis.XPendingCmd {
	return m.defaultConn.XPending(arg0, arg1, arg2)
}

func (m *Manager) XPendingExt(arg0 context.Context, arg1 *redis.XPendingExtArgs) *redis.XPendingExtCmd {
	return m.defaultConn.XPendingExt(arg0, arg1)
}

func (m *Manager) XRange(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.XMessageSliceCmd {
	return m.defaultConn.XRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) XRangeN(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 int64) *redis.XMessageSliceCmd {
	return m.defaultConn.XRangeN(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) XRead(arg0 context.Context, arg1 *redis.XReadArgs) *redis.XStreamSliceCmd {
	return m.defaultConn.XRead(arg0, arg1)
}

func (m *Manager) XReadGroup(arg0 context.Context, arg1 *redis.XReadGroupArgs) *redis.XStreamSliceCmd {
	return m.defaultConn.XReadGroup(arg0, arg1)
}

func (m *Manager) XReadStreams(arg0 context.Context, arg1 ...string) *redis.XStreamSliceCmd {
	return m.defaultConn.XReadStreams(arg0, arg1...)
}

func (m *Manager) XRevRange(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.XMessageSliceCmd {
	return m.defaultConn.XRevRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) XRevRangeN(arg0 context.Context, arg1 string, arg2 string, arg3 string, arg4 int64) *redis.XMessageSliceCmd {
	return m.defaultConn.XRevRangeN(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) XTrimMaxLen(arg0 context.Context, arg1 string, arg2 int64) *redis.IntCmd {
	return m.defaultConn.XTrimMaxLen(arg0, arg1, arg2)
}

func (m *Manager) XTrimMaxLenApprox(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.IntCmd {
	return m.defaultConn.XTrimMaxLenApprox(arg0, arg1, arg2, arg3)
}

func (m *Manager) XTrimMaxLenApproxMode(arg0 context.Context, arg1 string, arg2 int64, arg3 int64, arg4 string) *redis.IntCmd {
	return m.defaultConn.XTrimMaxLenApproxMode(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) XTrimMaxLenMode(arg0 context.Context, arg1 string, arg2 int64, arg3 string) *redis.IntCmd {
	return m.defaultConn.XTrimMaxLenMode(arg0, arg1, arg2, arg3)
}

func (m *Manager) XTrimMinID(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.XTrimMinID(arg0, arg1, arg2)
}

func (m *Manager) XTrimMinIDApprox(arg0 context.Context, arg1 string, arg2 string, arg3 int64) *redis.IntCmd {
	return m.defaultConn.XTrimMinIDApprox(arg0, arg1, arg2, arg3)
}

func (m *Manager) XTrimMinIDApproxMode(arg0 context.Context, arg1 string, arg2 string, arg3 int64, arg4 string) *redis.IntCmd {
	return m.defaultConn.XTrimMinIDApproxMode(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) XTrimMinIDMode(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.XTrimMinIDMode(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZAdd(arg0 context.Context, arg1 string, arg2 ...redis.Z) *redis.IntCmd {
	return m.defaultConn.ZAdd(arg0, arg1, arg2...)
}

func (m *Manager) ZAddArgs(arg0 context.Context, arg1 string, arg2 redis.ZAddArgs) *redis.IntCmd {
	return m.defaultConn.ZAddArgs(arg0, arg1, arg2)
}

func (m *Manager) ZAddArgsIncr(arg0 context.Context, arg1 string, arg2 redis.ZAddArgs) *redis.FloatCmd {
	return m.defaultConn.ZAddArgsIncr(arg0, arg1, arg2)
}

func (m *Manager) ZAddGT(arg0 context.Context, arg1 string, arg2 ...redis.Z) *redis.IntCmd {
	return m.defaultConn.ZAddGT(arg0, arg1, arg2...)
}

func (m *Manager) ZAddLT(arg0 context.Context, arg1 string, arg2 ...redis.Z) *redis.IntCmd {
	return m.defaultConn.ZAddLT(arg0, arg1, arg2...)
}

func (m *Manager) ZAddNX(arg0 context.Context, arg1 string, arg2 ...redis.Z) *redis.IntCmd {
	return m.defaultConn.ZAddNX(arg0, arg1, arg2...)
}

func (m *Manager) ZAddXX(arg0 context.Context, arg1 string, arg2 ...redis.Z) *redis.IntCmd {
	return m.defaultConn.ZAddXX(arg0, arg1, arg2...)
}

func (m *Manager) ZCard(arg0 context.Context, arg1 string) *redis.IntCmd {
	return m.defaultConn.ZCard(arg0, arg1)
}

func (m *Manager) ZCount(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.ZCount(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZDiff(arg0 context.Context, arg1 ...string) *redis.StringSliceCmd {
	return m.defaultConn.ZDiff(arg0, arg1...)
}

func (m *Manager) ZDiffStore(arg0 context.Context, arg1 string, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.ZDiffStore(arg0, arg1, arg2...)
}

func (m *Manager) ZDiffWithScores(arg0 context.Context, arg1 ...string) *redis.ZSliceCmd {
	return m.defaultConn.ZDiffWithScores(arg0, arg1...)
}

func (m *Manager) ZIncrBy(arg0 context.Context, arg1 string, arg2 float64, arg3 string) *redis.FloatCmd {
	return m.defaultConn.ZIncrBy(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZInter(arg0 context.Context, arg1 *redis.ZStore) *redis.StringSliceCmd {
	return m.defaultConn.ZInter(arg0, arg1)
}

func (m *Manager) ZInterCard(arg0 context.Context, arg1 int64, arg2 ...string) *redis.IntCmd {
	return m.defaultConn.ZInterCard(arg0, arg1, arg2...)
}

func (m *Manager) ZInterStore(arg0 context.Context, arg1 string, arg2 *redis.ZStore) *redis.IntCmd {
	return m.defaultConn.ZInterStore(arg0, arg1, arg2)
}

func (m *Manager) ZInterWithScores(arg0 context.Context, arg1 *redis.ZStore) *redis.ZSliceCmd {
	return m.defaultConn.ZInterWithScores(arg0, arg1)
}

func (m *Manager) ZLexCount(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.ZLexCount(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZMPop(arg0 context.Context, arg1 string, arg2 int64, arg3 ...string) *redis.ZSliceWithKeyCmd {
	return m.defaultConn.ZMPop(arg0, arg1, arg2, arg3...)
}

func (m *Manager) ZMScore(arg0 context.Context, arg1 string, arg2 ...string) *redis.FloatSliceCmd {
	return m.defaultConn.ZMScore(arg0, arg1, arg2...)
}

func (m *Manager) ZPopMax(arg0 context.Context, arg1 string, arg2 ...int64) *redis.ZSliceCmd {
	return m.defaultConn.ZPopMax(arg0, arg1, arg2...)
}

func (m *Manager) ZPopMin(arg0 context.Context, arg1 string, arg2 ...int64) *redis.ZSliceCmd {
	return m.defaultConn.ZPopMin(arg0, arg1, arg2...)
}

func (m *Manager) ZRandMember(arg0 context.Context, arg1 string, arg2 int) *redis.StringSliceCmd {
	return m.defaultConn.ZRandMember(arg0, arg1, arg2)
}

func (m *Manager) ZRandMemberWithScores(arg0 context.Context, arg1 string, arg2 int) *redis.ZSliceCmd {
	return m.defaultConn.ZRandMemberWithScores(arg0, arg1, arg2)
}

func (m *Manager) ZRange(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StringSliceCmd {
	return m.defaultConn.ZRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRangeArgs(arg0 context.Context, arg1 redis.ZRangeArgs) *redis.StringSliceCmd {
	return m.defaultConn.ZRangeArgs(arg0, arg1)
}

func (m *Manager) ZRangeArgsWithScores(arg0 context.Context, arg1 redis.ZRangeArgs) *redis.ZSliceCmd {
	return m.defaultConn.ZRangeArgsWithScores(arg0, arg1)
}

func (m *Manager) ZRangeByLex(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.StringSliceCmd {
	return m.defaultConn.ZRangeByLex(arg0, arg1, arg2)
}

func (m *Manager) ZRangeByScore(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.StringSliceCmd {
	return m.defaultConn.ZRangeByScore(arg0, arg1, arg2)
}

func (m *Manager) ZRangeByScoreWithScores(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.ZSliceCmd {
	return m.defaultConn.ZRangeByScoreWithScores(arg0, arg1, arg2)
}

func (m *Manager) ZRangeStore(arg0 context.Context, arg1 string, arg2 redis.ZRangeArgs) *redis.IntCmd {
	return m.defaultConn.ZRangeStore(arg0, arg1, arg2)
}

func (m *Manager) ZRangeWithScores(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.ZSliceCmd {
	return m.defaultConn.ZRangeWithScores(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRank(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.ZRank(arg0, arg1, arg2)
}

func (m *Manager) ZRankWithScore(arg0 context.Context, arg1 string, arg2 string) *redis.RankWithScoreCmd {
	return m.defaultConn.ZRankWithScore(arg0, arg1, arg2)
}

func (m *Manager) ZRem(arg0 context.Context, arg1 string, arg2 ...interface{}) *redis.IntCmd {
	return m.defaultConn.ZRem(arg0, arg1, arg2...)
}

func (m *Manager) ZRemRangeByLex(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.ZRemRangeByLex(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRemRangeByRank(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.IntCmd {
	return m.defaultConn.ZRemRangeByRank(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRemRangeByScore(arg0 context.Context, arg1 string, arg2 string, arg3 string) *redis.IntCmd {
	return m.defaultConn.ZRemRangeByScore(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRevRange(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.StringSliceCmd {
	return m.defaultConn.ZRevRange(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRevRangeByLex(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.StringSliceCmd {
	return m.defaultConn.ZRevRangeByLex(arg0, arg1, arg2)
}

func (m *Manager) ZRevRangeByScore(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.StringSliceCmd {
	return m.defaultConn.ZRevRangeByScore(arg0, arg1, arg2)
}

func (m *Manager) ZRevRangeByScoreWithScores(arg0 context.Context, arg1 string, arg2 *redis.ZRangeBy) *redis.ZSliceCmd {
	return m.defaultConn.ZRevRangeByScoreWithScores(arg0, arg1, arg2)
}

func (m *Manager) ZRevRangeWithScores(arg0 context.Context, arg1 string, arg2 int64, arg3 int64) *redis.ZSliceCmd {
	return m.defaultConn.ZRevRangeWithScores(arg0, arg1, arg2, arg3)
}

func (m *Manager) ZRevRank(arg0 context.Context, arg1 string, arg2 string) *redis.IntCmd {
	return m.defaultConn.ZRevRank(arg0, arg1, arg2)
}

func (m *Manager) ZRevRankWithScore(arg0 context.Context, arg1 string, arg2 string) *redis.RankWithScoreCmd {
	return m.defaultConn.ZRevRankWithScore(arg0, arg1, arg2)
}

func (m *Manager) ZScan(arg0 context.Context, arg1 string, arg2 uint64, arg3 string, arg4 int64) *redis.ScanCmd {
	return m.defaultConn.ZScan(arg0, arg1, arg2, arg3, arg4)
}

func (m *Manager) ZScore(arg0 context.Context, arg1 string, arg2 string) *redis.FloatCmd {
	return m.defaultConn.ZScore(arg0, arg1, arg2)
}

func (m *Manager) ZUnion(arg0 context.Context, arg1 redis.ZStore) *redis.StringSliceCmd {
	return m.defaultConn.ZUnion(arg0, arg1)
}

func (m *Manager) ZUnionStore(arg0 context.Context, arg1 string, arg2 *redis.ZStore) *redis.IntCmd {
	return m.defaultConn.ZUnionStore(arg0, arg1, arg2)
}

func (m *Manager) ZUnionWithScores(arg0 context.Context, arg1 redis.ZStore) *redis.ZSliceCmd {
	return m.defaultConn.ZUnionWithScores(arg0, arg1)
}
