// Code generated by export_config_package/export_package.go; DO NOT EDIT.
package config

import (
	"github.com/go-kratos/kratos/v2/config"
)

type Config = config.Config
type Decoder = config.Decoder
type KeyValue = config.KeyValue
type Merge = config.Merge
type Observer = config.Observer
type Option = config.Option
type Reader = config.Reader
type Resolver = config.Resolver
type Source = config.Source
type Value = config.Value
type Watcher = config.Watcher

var ErrNotFound = config.ErrNotFound
var New = config.New
var WithDecoder = config.WithDecoder
var WithMergeFunc = config.WithMergeFunc
var WithResolveActualTypes = config.WithResolveActualTypes
var WithResolver = config.WithResolver
var WithSource = config.WithSource

